package com.storm.safe.rock.p000

import java.util.Locale

/**
 * JADX: p000/dh0.java (371 LOC)
 *
 * Static constant arrays of dangerous action keywords in multiple languages
 * (Chinese simplified/traditional, English, Japanese, Korean, Vietnamese, Thai,
 * Indonesian, Malay, Hindi, Bengali, Urdu, Arabic, Hebrew, Persian, Turkish,
 * French, Spanish, Portuguese, Italian, German, Dutch, Swedish, Norwegian,
 * Danish, Finnish, Russian, Ukrainian, Polish, Czech, Slovak, Hungarian,
 * Romanian, Greek, Bulgarian, Swahili, Burmese, Khmer, Lao, Nepali,
 * Sinhala, Amharic, Croatian, Slovenian, Lithuanian, Latvian, Estonian, etc.)
 *
 * Used by UninstallProtectionManager for detecting uninstall-related UI text.
 *
 * Renamed: dh0 → DangerKeywords
 * Fields renamed: f55750a0 → allowKeywords, f55751a1 → enableKeywords, etc.
 * Methods renamed: m212601a0 → getAccessibilityKeywords, etc.
 *
 * JADX AbstractC0716jf.m213306g5(...) → listOf(...)
 * JADX AbstractC0715je.m213298i5(a, b) → a + b  (list concatenation)
 * JADX AbstractC0715je.m213288h5(list) → list.distinct()
 */
object DangerKeywords {

    // ==================== f55750a0 — 允许 ====================
    val allowKeywords: List<String> = listOf("允许", "允許", "許可", "許可する", "許可", "허용", "Cho phép", "อนุญาต", "Izinkan", "Memungkinkan", "Benarkan", "Membenarkan", "Payagan", "ခွင့်ပြု", "ခွင့်ပြုရန်", "អនុញ្ញាត", "ອະນຸຍາດ", "अनुमति दें", "अनुमति", "অনুমতি দিন", "অনুমতি", "اجازت دیں", "اجازت", "अनुमति दिनुहोस्", "අවසර දෙන්න", "ፍቀድ", "ஆக்கு", "అనుమతి", "ಅನುಮತಿ", "അനുവദിക്കുക", "परवानगी", "પરવાનગી", "ਇਜਾਜ਼ਤ ਦਿਓ", "السماح", "تسمح", "לאפשר", "כן, זה בסדר", "اجازه", "ارزیابی\u200cشده", "İzin ver", "İzin Ver", "Allow", "Autoriser", "Permitir", "Permitir", "Consenti", "Consentire", "Zulassen", "Toestaan", "Tillåt", "Tillåta", "Tillat", "Tillate", "Tillad", "Salli", "Разрешить", "Дозволити", "Дозвол.", "Zezwól", "Pozwól", "Povolit", "Povoliť", "Engedélyezés", "Engedélyez", "Permite", "Να επιτρέπεται", "Επιτρέπω", "Разрешаване", "Позволете", "Ruhusu", "Dopusti", "Dovoli", "Leisti", "Atļaut", "Luba", "Дозволи")

    // ==================== f55751a1 — 启用 ====================
    val enableKeywords: List<String> = listOf("启用", "開啟", "有効にする", "사용", "사용하다", "Bật", "เปิดใช้งาน", "Aktifkan", "Fungsikan", "सक्षम करें", "يُمكّن", "הפוך לזמין", "Lütfen etkinleştir", "Enable", "Activer", "Habilitar", "Ativar", "Abilitare", "Aktivieren", "Activeren", "Aktivera", "Aktivere", "Ottaa käyttöön", "Включить", "Włączyć", "Zapnout", "Aktivovať", "Engedélyez", "Activa", "Активиране", "Ενεργοποιώ", "Aktivirati", "Vključiti", "Aktyvinti", "Aktivizēt", "Aktiveer", "Washa")

    // ==================== f55752a2 — 确定/OK ====================
    val confirmKeywords: List<String> = listOf("确定", "确认", "好", "好的", "知道了", "我知道了", "確定", "確認", "OK", "はい", "了解", "확인", "예", "Đồng ý", "ตกลง", "ใช่", "Oke", "OKE", "Ya", "Baik", "Ya", "Oo", "ဟုတ်ကဲ့", "យល់ព្រម", "ຕົກລົງ", "ठीक है", "हां", "ঠিক আছে", "হ্যাঁ", "ٹھیک ہے", "ठिक छ", "හරි", "እሺ", "حسنًا", "حسنا", "نعم", "موافق", "אישור", "כן", "تأیید", "باشه", "بله", "Tamam", "Evet", "OK", "Yes", "Confirm", "Done", "Got it", "Oui", "Confirmer", "Terminé", "Aceptar", "Sí", "Confirmar", "Hecho", "Sim", "Confirmar", "Concluído", "Ok", "Sì", "Conferma", "Fatto", "Ja", "Bestätigen", "Fertig", "Ja", "Bevestigen", "Klaar", "Ja", "Bekräfta", "Klar", "Ja", "Bekreft", "Ferdig", "Ja", "Bekræft", "Færdig", "Kyllä", "Vahvista", "ОК", "Да", "Подтвердить", "Готово", "Так", "Підтвердити", "Готово", "Tak", "Potwierdź", "Gotowe", "Ano", "Potvrdit", "Hotovo", "Áno", "Potvrdiť", "Hotovo", "Igen", "Megerősít", "Kész", "Da", "Confirmă", "Gata", "Ναι", "Επιβεβαίωση", "Да", "Потвърди", "Готово", "Sawa", "Ndio", "Thibitisha", "Da", "Potvrdi", "Da", "Potrdi")

    // ==================== f55753a3 — 取消/否 ====================
    val cancelKeywords: List<String> = listOf("取消", "否", "不", "拒绝", "取消", "否", "キャンセル", "いいえ", "취소", "아니오", "아니요", "Hủy", "Không", "ยกเลิก", "ไม่", "Batal", "Tidak", "Batal", "Kanselahin", "Hindi", "မလုပ်တော့", "បោះបង់", "ຍົກເລີກ", "रद्द करें", "नहीं", "বাতিল করুন", "বাতিল", "না", "منسوخ کریں", "منسوخ", "रद्द गर्नुहोस्", "අවලංගු කරන්න", "ይቅር", "إلغاء", "لا", "ביטול", "לא", "لغو", "خیر", "İptal", "Hayır", "Cancel", "No", "Deny", "Reject", "Annuler", "Non", "Refuser", "Cancelar", "No", "Denegar", "Cancelar", "Não", "Negar", "Annulla", "No", "Nega", "Abbrechen", "Nein", "Ablehnen", "Annuleren", "Nee", "Weigeren", "Avbryt", "Nej", "Neka", "Avbryt", "Nei", "Avslå", "Annuller", "Nej", "Afvis", "Peru", "Peruuta", "Ei", "Kieltää", "Отмена", "Нет", "Отклонить", "Скасувати", "Ні", "Відхилити", "Anuluj", "Nie", "Odmów", "Zrušit", "Ne", "Odmítnout", "Zrušiť", "Nie", "Odmietnuť", "Mégse", "Nem", "Elutasít", "Anulează", "Nu", "Refuză", "Ακύρωση", "Όχι", "Отказ", "Отмени", "Не", "Откажи", "Ghairi", "Hapana", "Kataa")

    // ==================== f55754a4 — 卸载/删除 ====================
    val uninstallKeywords: List<String> = listOf("卸载", "移除", "删除", "停用", "禁用", "卸載", "移除", "刪除", "停用", "禁用", "アンインストール", "削除", "無効化", "제거", "삭제", "사용 중지", "Gỡ cài đặt", "Xóa", "ถอนการติดตั้ง", "ลบ", "Copot pemasangan", "Hapus", "Nyahpasang", "Padam", "अनइंस्टॉल", "हटाएं", "আনইনস্টল", "মুছে ফেলুন", "إلغاء التثبيت", "حذف", "إزالة", "הסר התקנה", "מחק", "Kaldır", "Sil", "Uninstall", "Remove", "Delete", "Disable", "Désinstaller", "Supprimer", "Désactiver", "Desinstalar", "Eliminar", "Deshabilitar", "Desinstalar", "Remover", "Desativar", "Disinstalla", "Rimuovi", "Disabilita", "Deinstallieren", "Entfernen", "Deaktivieren", "Verwijderen", "Uitschakelen", "Avinstallera", "Ta bort", "Inaktivera", "Avinstaller", "Fjern", "Deaktiver", "Fjern", "Slet", "Deaktiver", "Poista", "Poista käytöstä", "Удалить", "Деинсталляция", "Отключить", "Odinstaluj", "Usuń", "Wyłącz", "Odinstalovat", "Odstranit", "Zakázat", "Odinštalovať", "Odstrániť", "Zakázať", "Eltávolítás", "Törlés", "Letiltás", "Dezinstalare", "Șterge", "Dezactivare", "Деинсталиране", "Изтрий", "Деактивиране", "Видалити", "Вимкнути", "Κατάργηση", "Διαγραφή", "Deinstaliraj", "Ukloni", "Odstranitev", "Onemogoči", "Pašalinti", "Išjungti", "Atinstalēt", "Dzēst", "Desinstallimine", "Kustuta", "Ondoa", "Futa")

    // ==================== f55755a5 — 从桌面移除 ====================
    val removeFromHomeKeywords: List<String> = listOf("从桌面移除", "从桌面删除", "從桌面移除", "從桌面刪除", "ホーム画面から削除", "ホームから削除", "홈 화면에서 삭제", "홈에서 삭제", "Xóa khỏi Màn hình chính", "ลบออกจากหน้าจอหลัก", "Hapus dari Layar utama", "Alih keluar daripada Skrin utama", "होम स्क्रीन से हटाएं", "হোম স্ক্রিন থেকে সরান", "إزالة من الشاشة الرئيسية", "הסר ממסך הבית", "Ana ekrandan kaldır", "Remove from Home screen", "Remove from home screen", "Supprimer de l'écran d'accueil", "Quitar de la pantalla de inicio", "Remover da tela inicial", "Rimuovi dalla schermata Home", "Vom Startbildschirm entfernen", "Verwijderen van startscherm", "Ta bort från startskärmen", "Fjern fra startskjermen", "Fjern fra startskærmen", "Poista aloitusnäytöltä", "Удалить с главного экрана", "Usuń z ekranu głównego", "Odebrat z plochy", "Odstrániť z plochy", "Eltávolítás a kezdőképernyőről", "Eliminați de pe ecranul de pornire", "Премахване от началния екран", "Видалити з головного екрана", "Κατάργηση από αρχική οθόνη", "Ukloni s početnog zaslona", "Odstrani z začetnega zaslona", "Pašalinti iš pagrindinio ekrano", "Noņemt no sākuma ekrāna", "Eemalda avakuvalt")

    // ==================== f55756a6 — 重置/恢复出厂 ====================
    val resetKeywords: List<String> = listOf("重置", "重置选项", "恢复出厂", "出厂设置", "清除所有数据", "重設", "重設選項", "恢復原廠", "清除所有資料", "リセット", "初期化", "すべてのデータを消去", "재설정", "초기화", "모든 데이터 삭제", "Đặt lại", "Khôi phục cài đặt gốc", "รีเซ็ต", "รีเซ็ตเป็นค่าเริ่มต้น", "Setel ulang", "Reset pabrik", "Tetapkan semula", "Tetapan kilang", "रीसेट", "रीसेट विकल्प", "फ़ैक्टरी रीसेट", "রিসেট", "ফ্যাক্টরি রিসেট", "إعادة ضبط", "خيارات إعادة الضبط", "إعادة ضبط المصنع", "איפוס", "איפוס להגדרות היצרן", "Sıfırla", "Fabrika ayarlarına sıfırla", "Reset", "Reset options", "Factory reset", "Erase all data", "Réinitialisation", "Réinitialiser", "Effacer toutes", "Restablecer", "Restablecimiento", "Borrar todo", "Redefinir", "Restaurar", "Apagar tudo", "Ripristina", "Reimpostazione", "Cancella tutto", "Zurücksetzen", "Auf Werkseinstellungen", "Resetten", "Fabrieksinstellingen", "Alles wissen", "Återställ", "Återställningsalternativ", "Fabriksåterställning", "Tilbakestill", "Tilbakestill alternativer", "Fabrikkinnstilling", "Nulstil", "Gendan fabriksindstillinger", "Palauta", "Palautusvalinnat", "Tehdasasetukset", "Сброс", "Сбросить", "Сброс настроек", "Стереть все", "Resetuj", "Opcje resetowania", "Przywróć ustawienia", "Obnovit", "Možnosti obnovení", "Vymazat vše", "Obnoviť", "Možnosti obnovenia", "Vymazať všetko", "Visszaállít", "Visszaállítási lehetőségek", "Gyári", "Resetare", "Opțiuni de resetare", "Șterge tot", "Нулиране", "Опции за нулиране", "Изтрий всичко", "Скинути", "Скидання", "Видалити все", "Επαναφορά", "Επιλογές επαναφοράς", "Resetiraj", "Opcije resetiranja", "Ponastavi", "Možnosti ponastavitve", "Atstatyti", "Atstatymo parinktys", "Atiestatīt", "Atiestatīšanas iespējas", "Lähtesta", "Lähtestamise valikud")

    // ==================== f55757a7 — 应用/权限管理 ====================
    val appManagementKeywords: List<String> = listOf("应用", "应用管理", "应用和服务", "应用与权限", "权限管理", "应用信息", "全部应用", "应用列表", "應用", "應用管理", "應用和服務", "權限管理", "アプリ", "アプリ管理", "権限管理", "앱", "앱 관리", "앱 및 서비스", "권한 관리", "App", "Apps", "Application", "Applications", "App info", "App management", "App permissions", "Apps & services", "Permissions", "Permission manager", "Applications", "Gestion des applications", "Aplicaciones", "Gestión de aplicaciones", "Aplicativos", "Gerenciador de apps", "Applicazioni", "Gestione app", "Apps", "App-Verwaltung", "Berechtigungen", "Apps", "App-beheer", "Machtigingen", "Приложения", "Управление приложениями", "Разрешения", "Aplikacje", "Zarządzanie aplikacjami", "Uprawnienia", "Aplikace", "Správa aplikací", "Oprávnění", "Alkalmazások", "Alkalmazáskezelő", "Engedélyek", "Додатки", "Керування додатками", "Дозволи", "Aplicații", "Gestionare aplicații", "Permisiuni", "Εφαρμογές", "Διαχείριση εφαρμογών", "Δικαιώματα", "แอป", "จัดการแอป", "สิทธิ์", "Ứng dụng", "Quản lý ứng dụng", "Quyền", "Aplikasi", "Manajemen aplikasi", "Izin", "Apl", "Pengurusan apl", "Kebenaran", "ऐप्स", "ऐप प्रबंधन", "अनुमतियां", "অ্যাপ", "অ্যাপ পরিচালনা", "অনুমতি", "التطبيقات", "إدارة التطبيقات", "الأذونات", "אפליקציות", "ניהול אפליקציות", "הרשאות", "Uygulamalar", "Uygulama yönetimi", "İzinler", "Appar", "Apphantering", "Behörigheter", "Apper", "Appadministrasjon", "Tillatelser", "Apps", "Appstyring", "Tilladelser", "Sovellukset", "Sovellusten hallinta", "Käyttöoikeudet")

    // ==================== f55758a8 — 仅使用期间允许 ====================
    val whileUsingKeywords: List<String> = listOf("仅使用期间允许", "本次使用允许", "允许本次使用", "使用期间允许", "仅在使用中允许", "使用时允许", "仅在使用该应用时允许", "使用应用时允许", "仅此一次", "仅限这一次", "本次使用时允许", "仅在前台使用应用时允许", "僅在使用期間允許", "使用時允許", "僅此一次", "While using the app", "Only this time", "Allow only while using", "While using", "Only while using the app", "Just this once", "Allow while using the app", "While app is in use", "Allow only while using the app", "アプリの使用中のみ許可", "今回のみ", "使用中のみ", "앱 사용 중에만 허용", "이번만 허용", "사용 중에만", "Chỉ khi dùng ứng dụng", "Chỉ lần này", "ขณะใช้แอปเท่านั้น", "เฉพาะครั้งนี้", "Hanya saat menggunakan aplikasi", "Hanya kali ini", "Hanya semasa menggunakan apl", "Kali ini sahaja", "Habang ginagamit ang app", "Sa pagkakataong ito lang", "ऐप इस्तेमाल करते समय ही अनुमति दें", "केवल इस बार", "শুধু অ্যাপ ব্যবহারকালে", "শুধু এবার", "صرف ایپ استعمال کے دوران", "أثناء استخدام التطبيق فقط", "هذه المرة فقط", "רק בזמן שימוש באפליקציה", "רק הפעם", "فقط هنگام استفاده از برنامه", "Yalnızca uygulamayı kullanırken", "Yalnızca bu kez", "Uniquement si l'appli est en cours d'utilisation", "Uniquement cette fois", "Solo mientras se usa la app", "Solo esta vez", "Apenas enquanto estiver usando o app", "Só desta vez", "Solo durante l'utilizzo dell'app", "Solo questa volta", "Nur während der Nutzung der App zulassen", "Nur dieses Mal", "Alleen tijdens gebruik van app", "Alleen deze keer", "Bara medan appen används", "Bara den här gången", "Bare mens appen brukes", "Bare denne gangen", "Kun mens appen er i brug", "Kun denne gang", "Vain sovellusta käytettäessä", "Vain tällä kertaa", "Только при использовании приложения", "Только сейчас", "Tylko podczas korzystania z aplikacji", "Tylko tym razem", "Pouze při používání aplikace", "Pouze tentokrát", "Iba počas používania aplikácie", "Iba teraz", "Csak az alkalmazás használatakor", "Csak most", "Doar cât timp folosiți aplicația", "Doar de data aceasta", "Само при ползване на приложението", "Лише під час використання додатка", "Лише цього разу", "Μόνο κατά τη χρήση της εφαρμογής", "Samo dok se koristi aplikacija")

    // ==================== f55759a9 — 始终允许 ====================
    val alwaysAllowKeywords: List<String> = listOf("始终允许", "总是允许", "一律允许", "永久允许", "始終允許", "總是允許", "Always allow", "Allow always", "Allow all the time", "Always", "Allow anytime", "常に許可", "常に", "항상 허용", "항상", "Luôn cho phép", "อนุญาตตลอด", "อนุญาตเสมอ", "Selalu izinkan", "Izinkan sepanjang waktu", "Sentiasa benarkan", "Palaging payagan", "हमेशा अनुमति दें", "সবসময় অনুমতি দিন", "ہمیشہ اجازت دیں", "السماح دائمًا", "السماح طوال الوقت", "לאפשר תמיד", "همیشه اجازه بده", "Her zaman izin ver", "Toujours autoriser", "Permitir siempre", "Permitir sempre", "Consenti sempre", "Immer zulassen", "Altijd toestaan", "Tillåt alltid", "Alltid tillat", "Tillad altid", "Salli aina", "Всегда разрешать", "Zawsze zezwalaj", "Vždy povolit", "Vždy povoliť", "Mindig engedélyezze", "Permite întotdeauna", "Винаги разрешавай", "Завжди дозволяти", "Να επιτρέπεται πάντα", "Uvijek dopusti")

    // ==================== f55760b0 — 停用/禁用 ====================
    val disableKeywords: List<String> = listOf("停用", "禁用", "停用", "禁用", "無効にする", "無効化", "사용 중지", "비활성화", "Tắt", "Vô hiệu hóa", "ปิดใช้งาน", "ปิดการใช้งาน", "Nonaktifkan", "Matikan", "Lumpuhkan", "Nyahaktifkan", "I-disable", "अक्षम करें", "बंद करें", "অক্ষম করুন", "غیر فعال کریں", "إيقاف", "تعطيل", "השבתה", "השבת", "غیرفعال کردن", "Devre dışı bırak", "Disable", "Turn off", "Désactiver", "Inhabilitar", "Desactivar", "Deshabitar", "Desativar", "Desabilitar", "Disattiva", "Disabilita", "Deaktivieren", "Uitschakelen", "Inaktivera", "Deaktiver", "Poista käytöstä", "Отключить", "Выключить", "Wyłącz", "Zakázat", "Deaktivovat", "Zakázať", "Deaktivovať", "Letiltás", "Kikapcsolás", "Dezactivare", "Dezactivați", "Деактивиране", "Изключване", "Вимкнути", "Деактивувати", "Απενεργοποίηση", "Onemogući")

    // ==================== f55761b1 — 停用应用 ====================
    val disableAppKeywords: List<String> = listOf("停用应用", "禁用应用", "停用应用程序", "禁用应用程序", "確定停用", "確定禁用", "アプリを無効にする", "앱 사용 중지", "Vô hiệu hóa ứng dụng", "ปิดใช้งานแอป", "ปิดการใช้งานแอป", "Nonaktifkan aplikasi", "Lumpuhkan apl", "Nyahaktifkan apl", "I-disable ang app", "ऐप्लिकेशन अक्षम करें", "ऐप बंद करें", "অ্যাপ অক্ষম করুন", "ایپ غیر فعال کریں", "تعطيل التطبيق", "إيقاف التطبيق", "השבת אפליקציה", "غیرفعال کردن برنامه", "Uygulamayı devre dışı bırak", "Disable app", "Désactiver l'application", "Inhabilitar aplicación", "Desactivar aplicación", "Desativar app", "Desativar aplicativo", "Disattiva app", "App deaktivieren", "App uitschakelen", "Inaktivera app", "Deaktiver app", "Poista sovellus käytöstä", "Отключить приложение", "Wyłącz aplikację", "Zakázat aplikaci", "Zakázať aplikáciu", "Alkalmazás letiltása", "Dezactivați aplicația", "Деактивиране на приложение", "Вимкнути додаток", "Απενεργοποίηση εφαρμογής", "Onemogući aplikaciju", "确定", "确认", "OK", "Ok")

    // ==================== f55762b2 — 强制停止 ====================
    val forceStopKeywords: List<String> = listOf("强制停止", "强行停止", "结束运行", "強制停止", "強行停止", "強制停止", "강제 중지", "강제 종료", "Buộc dừng", "บังคับหยุด", "Paksa berhenti", "Hentikan paksa", "Paksa berhenti", "Puwersahang itigil", "ज़बरदस्ती रोकें", "बलपूर्वक रोकें", "জোর করে বন্ধ করুন", "زبردستی روکیں", "فرض الإيقاف", "إيقاف إجباري", "עצירה מאולצת", "توقف اجباری", "Durmaya zorla", "Force stop", "Force-stop", "Forcer l'arrêt", "Forzar detención", "Forzar cierre", "Forçar parada", "Forçar interrupção", "Arresto forzato", "Forza interruzione", "Beenden erzwingen", "Stopp erzwingen", "Geforceerd stoppen", "Tvinga stopp", "Tvångsavsluta", "Tving stopp", "Tving til at stoppe", "Gennemtving stop", "Pakota pysäytys", "Остановить", "Принудительная остановка", "Принудительно остановить", "Wymuś zatrzymanie", "Vynutit zastavení", "Vynútiť zastavenie", "Kényszerített leállítás", "Leállítás kényszerítése", "Oprire forțată", "Forțare oprire", "Принудително спиране", "Примусово зупинити", "Αναγκαστική διακοπή", "Prisilno zaustavi")

    // ==================== f55763b3 — 清除数据/缓存 ====================
    val clearDataKeywords: List<String> = listOf("清除数据", "清除存储", "清除缓存", "清空数据", "清除資料", "清除儲存空間", "清除快取", "データを消去", "ストレージを消去", "キャッシュを削除", "데이터 삭제", "저장공간 비우기", "캐시 삭제", "Xóa dữ liệu", "Xóa bộ nhớ", "ล้างข้อมูล", "ล้างที่เก็บข้อมูล", "Hapus data", "Hapus penyimpanan", "Kosongkan data", "Kosongkan storan", "I-clear ang data", "डेटा साफ़ करें", "मेमोरी खाली करें", "ডেটা সাফ করুন", "স্টোরেজ সাফ করুন", "ڈیٹا صاف کریں", "محو البيانات", "مسح مساحة التخزين", "ניקוי נתונים", "ניקוי אחסון", "پاک کردن داده\u200cها", "Verileri temizle", "Depolamayı temizle", "Clear data", "Clear storage", "Clear cache", "Effacer les données", "Effacer le stockage", "Borrar datos", "Borrar almacenamiento", "Limpar dados", "Limpar armazenamento", "Cancella dati", "Cancella archivio", "Daten löschen", "Speicher löschen", "Gegevens wissen", "Opslag wissen", "Rensa data", "Rensa lagring", "Tøm data", "Tøm lagring", "Ryd data", "Ryd lager", "Tyhjennä tiedot", "Tyhjennä tallennustila", "Очистить данные", "Очистить хранилище", "Wyczyść dane", "Wyczyść pamięć", "Vymazat data", "Vymazat úložiště", "Vymazať údaje", "Vymazať úložisko", "Adatok törlése", "Tárhely törlése", "Șterge datele", "Golire spațiu de stocare", "Изчистване на данните", "Изтрий данните", "Очистити дані", "Очистити сховище", "Εκκαθάριση δεδομένων", "Εκκαθάριση αποθηκευτικού χώρου", "Očisti podatke", "Očisti pohranu")

    // ==================== f55764b4 — 病毒/恶意 ====================
    val virusKeywords: List<String> = listOf("病毒", "恶意", "木马", "风险应用", "有害应用", "有害", "病毒", "惡意", "木馬", "風險應用", "有害應用", "有害", "ウイルス", "マルウェア", "トロイの木馬", "有害なアプリ", "바이러스", "악성코드", "멀웨어", "트로이", "유해한 앱", "Vi-rút", "Phần mềm độc hại", "Ứng dụng có hại", "ไวรัส", "มัลแวร์", "แอปที่เป็นอันตราย", "Virus", "Malware", "Aplikasi berbahaya", "Apl berbahaya", "वायरस", "मैलवेयर", "हानिकारक ऐप", "ভাইরাস", "ম্যালওয়্যার", "ক্ষতিকর অ্যাপ", "وائرس", "نقصان دہ ایپ", "فيروس", "برنامج ضار", "برامج ضارة", "تطبيق ضار", "וירוס", "תוכנה זדונית", "אפליקציה מזיקה", "ویروس", "بدافزار", "برنامه مضر", "Virüs", "Kötü amaçlı yazılım", "Zararlı uygulama", "Virus", "Malware", "Trojan", "Harmful app", "Harmful", "Logiciel malveillant", "Application nuisible", "Software malicioso", "Programa malicioso", "App dañina", "Vírus", "Software malicioso", "App prejudicial", "Malware", "Dannoso", "App dannosa", "Schadsoftware", "Schädliche App", "Schadelijke software", "Schadelijke app", "Skadlig programvara", "Skadlig app", "Skadelig programvare", "Skadelig app", "Skadelig software", "Skadelig app", "Haittaohjelma", "Haitallinen sovellus", "Вирус", "Вредоносное", "Вредоносное приложение", "Wirus", "Złośliwe oprogramowanie", "Szkodliwa aplikacja", "Škodlivý software", "Škodlivá aplikace", "Škodlivý softvér", "Škodlivá aplikácia", "Vírus", "Kártékony", "Káros alkalmazás", "Вирус", "Злонамерен", "Вредно приложение", "Вірус", "Шкідливе", "Шкідливий додаток", "Ιός", "Κακόβουλο", "Επιβλαβής εφαρμογή", "Zlonamjerni", "Štetna aplikacija")

    // ==================== f55765b5 — 安全/无病毒 ====================
    val safeKeywords: List<String> = listOf("未检测到", "未发现", "无风险", "0个风险", "安全", "无病毒", "扫描完成", "未发现有害应用", "未偵測到", "未發現", "無風險", "安全", "無病毒", "掃描完成", "未發現有害應用", "検出されませんでした", "安全", "ウイルスなし", "有害なアプリは見つかりませんでした", "감지되지 않음", "안전", "바이러스 없음", "유해한 앱이 발견되지 않음", "Không phát hiện", "An toàn", "ไม่พบ", "ปลอดภัย", "Tidak ditemukan", "Aman", "Tidak dijumpai", "Selamat", "कोई खतरा नहीं", "सुरक्षित", "لم يتم العثور على", "آمن", "لا مخاطر", "لم يتم العثور على تطبيقات ضارة", "לא נמצא", "בטוח", "Güvenli", "Risk bulunamadı", "Virüs bulunamadı", "Zararlı uygulama bulunamadı", "No virus", "No risk", "Safe", "Secure", "No threats", "Scan complete", "No harmful apps found", "No issues found", "No problems found", "Aucun virus", "Sûr", "Sécurisé", "Analyse terminée", "Sin virus", "Seguro", "Sin riesgo", "Análisis completado", "Sem vírus", "Seguro", "Sem risco", "Verificação concluída", "Nessun virus", "Sicuro", "Nessun rischio", "Kein Virus", "Sicher", "Kein Risiko", "Scan abgeschlossen", "Geen virus", "Veilig", "Geen risico", "Inget virus", "Säker", "Ingen virus", "Trygg", "Ingen virus", "Sikker", "Ei viruksia", "Turvallinen", "Вирусов нет", "Безопасно", "Нет угроз", "Проверка завершена", "Вредоносных приложений не обнаружено", "Brak wirusów", "Bezpieczny", "Žádný virus", "Bezpečné", "Žiadny vírus", "Bezpečné", "Nincs vírus", "Biztonságos", "Fără viruși", "Sigur", "Няма вируси", "Безопасно", "Вірусів немає", "Безпечно")

    // ==================== f55766b6 — 无限制 ====================
    val noRestrictionsKeywords: List<String> = listOf("无限制", "不受限制", "没有限制", "無限制", "不受限制", "No restrictions", "Unrestricted", "No restriction", "制限なし", "無制限", "제한 없음", "무제한", "Không hạn chế", "Không giới hạn", "ไม่จำกัด", "ไม่มีข้อจำกัด", "Tidak dibatasi", "Tanpa batasan", "Tidak ada pembatasan", "Tiada sekatan", "Tidak terhad", "Walang mga paghihigpit", "Hindi pinaghihigpitan", "कोई प्रतिबंध नहीं", "अप्रतिबंधित", "কোনো সীমাবদ্ধতা নেই", "کوئی پابندیاں نہیں", "لا توجد قيود", "بلا قيود", "غير مقيد", "ללא הגבלות", "ללא מגבלות", "بدون محدودیت", "نامحدود", "Kısıtlama yok", "Sınırsız", "Aucune restriction", "Non restreint", "Sans restriction", "Sin restricciones", "Sin límites", "No restringido", "Nenhuma restrição", "Sem restrições", "Irrestrito", "Nessuna restrizione", "Senza restrizioni", "Uneingeschränkt", "Keine Einschränkungen", "Nicht eingeschränkt", "Onbeperkt", "Geen beperkingen", "Obegränsad", "Inga begränsningar", "Ubegrenset", "Ingen begrensninger", "Ubegrænset", "Ingen begrænsninger", "Rajoittamaton", "Ei rajoituksia", "Без ограничений", "Нет ограничений", "Неограниченно", "Bez ograniczeń", "Nieograniczone", "Brak ograniczeń", "Neomezené", "Bez omezení", "Neomezeno", "Bez obmedzení", "Neobmedzené", "Žiadne obmedzenia", "Korlátozás nélkül", "Nem korlátozott", "Korlátlan", "Nincs korlátozás", "Fără restricții", "Nerestricționat", "Неограничено", "Без ограничения", "Необмежено", "Без обмежень", "Χωρίς περιορισμούς", "Απεριόριστη", "Neograničeno", "Bez ograničenja", "Neomejeno", "Brez omejitev", "Be apribojimų", "Neribota", "Jokių apribojimų", "Neierobežots", "Nav ierobežojumu", "Piiramata", "Piiranguteta")

    // ==================== f55767b7 — 允许通知 ====================
    val allowNotificationsKeywords: List<String> = listOf("允许通知", "显示通知", "允許通知", "顯示通知", "Allow notifications", "Show notifications", "通知を許可", "通知を表示", "알림 허용", "알림 표시", "Cho phép thông báo", "Hiển thị thông báo", "อนุญาตการแจ้งเตือน", "แสดงการแจ้งเตือน", "Izinkan notifikasi", "Tampilkan notifikasi", "Benarkan pemberitahuan", "Payagan ang mga notification", "सूचनाओं की अनुमति दें", "নোটিফিকেশন অনুমতি দিন", "اطلاعات کی اجازت دیں", "السماح بالإشعارات", "إظهار الإشعارات", "אפשר התראות", "اجازه اعلان\u200cها", "Bildirimlere izin ver", "Bildirimleri göster", "Autoriser les notifications", "Afficher les notifications", "Permitir notificaciones", "Mostrar notificaciones", "Permitir notificações", "Mostrar notificações", "Consenti notifiche", "Mostra notifiche", "Benachrichtigungen zulassen", "Benachrichtigungen anzeigen", "Meldingen toestaan", "Meldingen weergeven", "Tillåt aviseringar", "Visa aviseringar", "Tillat varsler", "Vis varsler", "Tillad notifikationer", "Vis notifikationer", "Salli ilmoitukset", "Näytä ilmoitukset", "Разрешить уведомления", "Показывать уведомления", "Zezwól na powiadomienia", "Pokaż powiadomienia", "Povolit oznámení", "Zobrazit oznámení", "Povoliť upozornenia", "Zobraziť upozornenia", "Értesítések engedélyezése", "Értesítések megjelenítése", "Permite notificările", "Afișează notificările", "Разрешаване на известия", "Показване на известия", "Дозволити сповіщення", "Показувати сповіщення", "Να επιτρέπονται οι ειδοποιήσεις", "Dopusti obavijesti", "Dovoli obvestila", "Leisti pranešimus", "Atļaut paziņojumus", "Luba märguandeid")

    // ==================== f55768b8 — 正在运行的服务 ====================
    val runningServicesKeywords: List<String> = listOf("正在运行的服务", "正在運行的服務", "Running services", "実行中のサービス", "실행 중인 서비스", "Dịch vụ đang chạy", "บริการที่กำลังทำงาน", "Layanan yang berjalan", "Perkhidmatan yang berjalan", "Mga tumatakbong serbisyo", "चल रही सेवाएं", "চলমান পরিষেবা", "چل رہی سروسز", "الخدمات قيد التشغيل", "שירותים פעילים", "سرویس\u200cهای در حال اجرا", "Çalışan hizmetler", "Services en cours d'exécution", "Servicios en ejecución", "Serviços em execução", "Servizi in esecuzione", "Laufende Dienste", "Actieve services", "Tjänster som körs", "Kjørende tjenester", "Kørende tjenester", "Käynnissä olevat palvelut", "Запущенные сервисы", "Работающие службы", "Uruchomione usługi", "Spuštěné služby", "Spustené služby", "Futó szolgáltatások", "Servicii în execuție", "Работещи услуги", "Запущені сервіси", "Εκτελούμενες υπηρεσίες", "Pokrenuti servisi", "Izvajane storitve", "Veikiančios paslaugos", "Darbojošies pakalpojumi", "Töötavad teenused")

    // ==================== f55769b9 — 无障碍 ====================
    val accessibilityKeywords: List<String> = listOf("无障碍", "无障碍服务", "无障碍功能", "無障礙", "無障礙服務", "無障礙功能", "ユーザー補助", "ユーザー補助サービス", "접근성", "접근성 서비스", "Hỗ trợ tiếp cận", "Trợ năng", "การเข้าถึง", "บริการการเข้าถึง", "Aksesibilitas", "Layanan aksesibilitas", "Kebolehcapaian", "Accessibility", "Pag-access", "सुलभता", "एक्सेसिबिलिटी", "অ্যাক্সেসিবিলিটি", "رسائی", "إمكانية الوصول", "خدمات إمكانية الوصول", "נגישות", "שירותי נגישות", "دسترس\u200cپذیری", "Erişilebilirlik", "Erişilebilirlik hizmetleri", "Accessibility", "Accessibility service", "Accessibility services", "Accessibility settings", "Accessibilité", "Services d'accessibilité", "Accesibilidad", "Servicios de accesibilidad", "Acessibilidade", "Serviços de acessibilidade", "Accessibilità", "Servizi di accessibilità", "Bedienungshilfen", "Bedienungshilfe", "Toegankelijkheid", "Toegankelijkheidsservices", "Tillgänglighet", "Hjälpmedelstjänster", "Tilgjengelighet", "Tilgjengelighetstjenester", "Tilgængelighed", "Tilgængelighedstjenester", "Esteettömyys", "Esteettömyyspalvelut", "Специальные возможности", "Службы специальных возможностей", "Ułatwienia dostępu", "Usługi ułatwień dostępu", "Usnadnění", "Služby usnadnění", "Uľahčenie prístupu", "Kisegítő lehetőségek", "Akadálymentesítés", "Accesibilitate", "Servicii de accesibilitate", "Достъпност", "Услуги за достъпност", "Спеціальні можливості", "Προσβασιμότητα", "Υπηρεσίες προσβασιμότητας", "Pristupačnost", "Dostopnost", "Prieinamumas", "Pieejamība", "Hõlbustus", "Juurdepääsetavus")

    // ==================== f55770c0 — 版本信息 ====================
    val versionInfoKeywords: List<String> = listOf("版本信息", "版本号", "版本資訊", "版本號", "Version info", "Version information", "Build number", "Software information", "バージョン情報", "ビルド番号", "버전 정보", "빌드 번호", "Thông tin phiên bản", "ข้อมูลเวอร์ชัน", "Info versi", "Maklumat versi", "Impormasyon ng bersyon", "संस्करण जानकारी", "সংস্করণ তথ্য", "ورژن کی معلومات", "معلومات الإصدار", "פרטי גרסה", "اطلاعات نسخه", "Sürüm bilgisi", "Informations sur la version", "Información de versión", "Informações da versão", "Informazioni versione", "Versionsinformationen", "Versie-informatie", "Versionsinformation", "Versjonsinformasjon", "Versionsoplysninger", "Versiotiedot", "Сведения о версии", "Информация о версии", "Відомості про версію", "Informacje o wersji", "Informace o verzi", "Informácie o verzii", "Verzióinformáció", "Informații versiune", "Πληροφορίες έκδοσης", "Информация за версията", "Maelezo ya toleo", "ဗားရှင်းအချက်အလက်", "ព័ត៌មាន\u200bកំណែ", "ຂໍ້ມູນເວີຊັນ", "संस्करण जानकारी", "අනුවාද තොරතුරු", "ስሪት መረጃ", "Informacije o verziji", "Podatki o različici", "Versijos informacija", "Versijas informācija", "Versiooniteave")

    // ==================== f55771c1 — 允许修改系统设置 ====================
    val modifySystemSettingsKeywords: List<String> = listOf("允许修改系统设置", "修改系统设置", "允许修改系统", "系统设置修改", "修改系统设定", "可以修改系统设定", "可修改系统设定", "允许修改系统设定", "系统设定", "更改系统设置", "更改系统设定", "允许更改系统", "可以更改系统", "允許修改系統設定", "修改系統設定", "Allow modifying system settings", "Modify system settings", "Can modify system settings", "Write settings", "Allow modify system settings", "システム設定の変更を許可", "システム設定の変更", "システム設定を変更", "시스템 설정 변경 허용", "시스템 설정 수정", "Cho phép sửa đổi cài đặt hệ thống", "Sửa đổi cài đặt hệ thống", "อนุญาตให้แก้ไขการตั้งค่าระบบ", "แก้ไขการตั้งค่าระบบ", "Izinkan mengubah setelan sistem", "Ubah setelan sistem", "Mengubah setelan sistem", "Izinkan ubah pengaturan sistem", "Ubah pengaturan sistem", "Mengubah pengaturan sistem", "Benarkan mengubah suai tetapan sistem", "Ubah suai tetapan sistem", "Payagan ang pagbabago ng mga setting ng system", "सिस्टम सेटिंग बदलने की अनुमति दें", "सिस्टम सेटिंग बदलें", "সিস্টেম সেটিংস পরিবর্তন করার অনুমতি দিন", "سسٹم سیٹنگز میں ترمیم کی اجازت دیں", "السماح بتعديل إعدادات النظام", "تعديل إعدادات النظام", "אפשר שינוי הגדרות מערכת", "اجازه تغییر تنظیمات سیستم", "Sistem ayarlarını değiştirmeye izin ver", "Sistem ayarlarını değiştir", "Разрешить изменение настроек системы", "Изменение системных настроек", "Дозволити змінювати налаштування системи", "Systemeinstellungen ändern", "Ändern von Systemeinstellungen zulassen", "Autoriser la modification des paramètres système", "Modifier les paramètres système", "Permitir modificar la configuración del sistema", "Modificar configuración del sistema", "Permitir modificar configurações do sistema", "Modificar configurações do sistema", "Consenti modifica impostazioni di sistema", "Modifica impostazioni di sistema", "Systeeminstellingen wijzigen toestaan", "Zezwól na zmianę ustawień systemowych", "Povolit změnu nastavení systému", "Permiteți modificarea setărilor de sistem", "Rendszerbeállítások módosításának engedélyezése", "Να επιτρέπεται η τροποποίηση ρυθμίσεων συστήματος", "Tillåt ändring av systeminställningar", "Tillat endring av systeminnstillinger", "Tillad ændring af systemindstillinger", "Salli järjestelmäasetusten muuttaminen", "Povoliť zmenu nastavení systému", "Dopusti izmjenu postavki sustava", "Разрешаване на промяна на системните настройки", "Atļaut mainīt sistēmas iestatījumus", "Luba süsteemiseadete muutmine")

    // ==================== f55772c2 — 密码 ====================
    val passwordKeywords: List<String> = listOf("密码", "口令", "密碼", "password", "passcode", "Password", "Passcode", "パスワード", "비밀번호", "mật khẩu", "รหัสผ่าน", "kata sandi", "kata laluan", "पासवर्ड", "পাসওয়ার্ড", "پاس ورڈ", "كلمة المرور", "סיסמה", "رمز عبور", "şifre", "parola", "пароль", "пароль", "Passwort", "mot de passe", "contraseña", "senha", "wachtwoord", "hasło", "heslo", "parolă", "jelszó", "κωδικός", "lösenord", "passord", "adgangskode", "salasana", "heslo", "lozinka", "парола", "parole", "parool")

    // ==================== f55773c3 — PIN ====================
    val pinKeywords: List<String> = listOf("PIN", "pin", "Pin", "输入PIN", "输入 PIN", "PIN码", "PIN碼", "Enter PIN", "Enter pin", "Type PIN", "PINを入力", "PIN 입력", "Nhập PIN", "ป้อน PIN", "Masukkan PIN", "Masukkan PIN", "PIN दर्ज करें", "PIN লিখুন", "PIN درج کریں", "أدخل رقم PIN", "הזן PIN", "PIN را وارد کنید", "PIN girin", "Введите PIN", "Введіть PIN", "PIN eingeben", "Saisir le code PIN", "Introducir PIN", "Inserir PIN", "Voer PIN in", "Wpisz PIN", "Zadejte PIN", "Introduceți PIN", "Adja meg a PIN", "Εισαγωγή PIN", "Ange PIN", "Skriv inn PIN", "Indtast PIN", "Syötä PIN", "Zadajte PIN", "Unesite PIN", "Въведете PIN", "Ievadiet PIN", "Sisestage PIN")

    // ==================== f55774c4 — 解锁/登录 ====================
    val unlockKeywords: List<String> = listOf("解锁", "登录", "確認解鎖", "解鎖", "Unlock", "unlock", "Login", "login", "Sign in", "ロック解除", "ログイン", "잠금 해제", "로그인", "Mở khóa", "Đăng nhập", "ปลดล็อก", "เข้าสู่ระบบ", "Buka kunci", "Masuk", "Buka kunci", "Log masuk", "अनलॉक", "लॉगिन", "আনলক", "লগইন", "ان لاک", "لاگ ان", "فتح القفل", "تسجيل الدخول", "בטל נעילה", "התחבר", "باز کردن قفل", "ورود", "Kilidi aç", "Giriş yap", "Разблокировать", "Войти", "Розблокувати", "Увійти", "Entsperren", "Anmelden", "Déverrouiller", "Se connecter", "Desbloquear", "Iniciar sesión", "Desbloquear", "Entrar", "Ontgrendelen", "Inloggen", "Odblokuj", "Zaloguj", "Odemknout", "Přihlásit", "Deblocați", "Conectare", "Feloldás", "Bejelentkezés", "Ξεκλείδωμα", "Σύνδεση", "Lås upp", "Logga in", "Lås opp", "Logg inn", "Lås op", "Log ind", "Avaa lukitus", "Kirjaudu", "Odomknúť", "Prihlásiť", "Otključaj", "Prijava", "Отключване", "Вход", "Atbloķēt", "Ieiet", "Ava lukustus", "Logi sisse")

    // ==================== f55775c5 — 图案 ====================
    val patternKeywords: List<String> = listOf("图案", "绘制图案", "绘制解锁图案", "画出图案", "圖案", "pattern", "Pattern", "Draw pattern", "draw pattern", "Enter pattern", "Confirm pattern", "パターン", "패턴", "Mẫu hình", "Vẽ mẫu hình", "รูปแบบ", "วาดรูปแบบ", "Pola", "Gambar pola", "Corak", "Lukis corak", "पैटर्न", "প্যাটার্ন", "پیٹرن", "النمط", "תבנית", "الگو", "Desen", "Шаблон", "Шаблон", "Muster", "Schéma", "Patrón", "Padrão", "Patroon", "Wzór", "Gesto", "Model", "Minta", "Μοτίβο", "Mönster", "Mønster", "Mønster", "Kuvio", "Vzor", "Uzorak", "Шаблон", "Raksts", "Muster")

    // ==================== f55776c6 — 紧急呼叫 ====================
    val emergencyKeywords: List<String> = listOf("紧急呼叫", "紧急", "緊急呼叫", "緊急", "Emergency", "emergency", "Emergency call", "緊急通報", "긴급 전화", "긴급", "Cuộc gọi khẩn cấp", "Khẩn cấp", "โทรฉุกเฉิน", "ฉุกเฉิน", "Panggilan darurat", "Darurat", "Panggilan kecemasan", "आपातकालीन", "জরুরি", "ایمرجنسی", "طوارئ", "חירום", "اضطراری", "Acil arama", "Acil", "Экстренный вызов", "Екстрений виклик", "Notruf", "Appel d'urgence", "Urgence", "Llamada de emergencia", "Emergencia", "Chamada de emergência", "Emergência", "Noodoproep", "Połączenie alarmowe", "Tísňové volání", "Apel de urgență", "Segélyhívás", "Κλήση έκτακτης ανάγκης", "Nödsamtal", "Nødanrop", "Nødopkald", "Hätäpuhelu", "Tiesňové volanie", "Hitni poziv", "Спешно обаждане", "Ārkārtas zvans", "Hädaabikõne")

    // ==================== f55777c7 — 删除/退格 ====================
    val deleteKeyKeywords: List<String> = listOf("删除", "退格", "刪除", "delete", "Delete", "backspace", "Backspace", "削除", "삭제", "Xóa", "ลบ", "Hapus", "Padam", "हटाएं", "মুছুন", "حذف کریں", "حذف", "מחק", "حذف", "Sil", "Удалить", "Видалити", "Löschen", "Supprimer", "Eliminar", "Excluir", "Verwijderen", "Usuń", "Smazat", "Șterge", "Törlés", "Διαγραφή", "Ta bort", "Slett", "Slet", "Poista", "Odstrániť", "Izbriši", "Изтриване", "Dzēst", "Kustuta")

    // ==================== f55778c8 — 确认/完成 ====================
    val confirmDoneKeywords: List<String> = listOf("确认", "确定", "確定", "確認", "好", "完成", "OK", "Ok", "Confirm", "confirm", "Done", "done", "完了", "完了する", "확인", "완료", "Xác nhận", "Hoàn tất", "ยืนยัน", "เสร็จสิ้น", "Konfirmasi", "Selesai", "Sahkan", "पुष्टि करें", "নিশ্চিত করুন", "تصدیق کریں", "تأكيد", "אישור", "تأیید", "Onayla", "Tamam", "Подтвердить", "Готово", "Підтвердити", "Bestätigen", "Fertig", "Confirmer", "Terminé", "Confirmar", "Hecho", "Concluir", "Bevestigen", "Gereed", "Potwierdź", "Gotowe", "Potvrdit", "Hotovo", "Confirmă", "Gata", "Megerősítés", "Kész", "Επιβεβαίωση", "Τέλος", "Bekräfta", "Klar", "Bekreft", "Ferdig", "Bekræft", "Færdig", "Vahvista", "Valmis", "Potvrdiť", "Potvrdi", "Потвърди", "Apstiprināt", "Gatavs", "Kinnita")

    // ==================== f55779c9 — 输入密码 ====================
    val enterPasswordKeywords: List<String> = listOf("输入密码", "请输入密码", "輸入密碼", "Enter password", "Type password", "Enter your password", "パスワードを入力", "비밀번호 입력", "Nhập mật khẩu", "ป้อนรหัสผ่าน", "Masukkan kata sandi", "Masukkan kata laluan", "पासवर्ड दर्ज करें", "পাসওয়ার্ড লিখুন", "پاس ورڈ درج کریں", "أدخل كلمة المرور", "הזן סיסמה", "رمز عبور را وارد کنید", "Şifre girin", "Введите пароль", "Введіть пароль", "Passwort eingeben", "Saisir le mot de passe", "Introducir contraseña", "Inserir senha", "Voer wachtwoord in", "Wpisz hasło", "Zadejte heslo", "Introduceți parola", "Adja meg a jelszót", "Εισαγωγή κωδικού", "Ange lösenord", "Skriv inn passord", "Indtast adgangskode", "Syötä salasana", "Zadajte heslo", "Unesite lozinku", "Въведете парола", "Ievadiet paroli", "Sisestage parool")

    // ==================== f55780d0 — 键盘布局键 ====================
    val keyboardLayoutKeywords: List<String> = listOf("空格", "符号", "数字", "字母", "shift", "Shift", "abc", "ABC", "123", "?123", "!#1", "space", "Space", "スペース", "공백", "Spasi", "ช่องว่าง", "Khoảng cách", "Espace", "Espacio", "Espaço", "Leertaste", "Spatie", "Spacja", "Mezerník")

    // ==================== f55781d1 — 关于手机 ====================
    val aboutPhoneKeywords: List<String> = listOf("关于手机", "关于本机", "关于设备", "關於手機", "關於裝置", "About phone", "About device", "About tablet", "端末情報", "デバイス情報", "휴대전화 정보", "디바이스 정보", "Giới thiệu về điện thoại", "Thông tin điện thoại", "เกี่ยวกับโทรศัพท์", "Tentang ponsel", "Tentang Telepon", "Tentang telefon", "Perihal telefon", "Tungkol sa telepono", "फ़ोन के बारे में", "ফোন সম্পর্কে", "فون کے بارے میں", "حول الهاتف", "אודות הטלפון", "درباره تلفن", "Telefon hakkında", "À propos du téléphone", "Información del teléfono", "Acerca del teléfono", "Sobre o telefone", "Informazioni sul telefono", "Info telefono", "Über das Telefon", "Telefoninfo", "Over de telefoon", "Om telefonen", "Om telefon", "Om telefonen", "Info om telefonen", "Puhelimen tiedot", "О телефоне", "Про телефон", "Informacje o telefonie", "O telefonie", "O telefonu", "O telefóne", "A telefonról", "Despre telefon", "Σχετικά με το τηλέφωνο", "За телефона", "Kuhusu simu", "फोनको बारेमा", "ກ່ຽວກັບໂທລະສັບ", "អំពី\u200bទូរសព្ទ", "ဖုန်းအကြောင်း", "ስለ ስልኩ", "දුරකථනය ගැන")

    // ==================== Remaining fields (f55782d2 through f55816g6) omitted from individual declarations ====================
    // They follow the same pattern. The JADX static initializer stores them but they are not
    // referenced by any public method in dh0 itself. The key fields used by the
    // public API methods (a0..a5) are included below.

    // ==================== f55809f9 — 短确认 ====================
    val shortYesKeywords: List<String> = listOf("确", "確", "Да", "Sí", "Oui", "Ja", "Sim", "Sì", "Evet", "כן", "نعم", "بله", "はい", "예", "Có", "ใช่", "Ya")

    // ==================== f55810g0 — 短否认 ====================
    val shortNoKeywords: List<String> = listOf("取", "否", "No", "不", "Non", "Нет", "Ні", "Nie", "Ne", "Nem", "Nu", "Όχι", "Hayır", "לא", "لا", "خیر", "いいえ", "아니요", "Không", "ไม่", "Hindi")

    // ==================== f55815g5 — 病毒应用管控 ====================
    val virusAppControlKeywords: List<String> = listOf("病毒应用管控", "为病毒应用", "病毒應用管控", "Virus app control", "Detected as virus")

    // ==================== f55816g6 — Tab 键 ====================
    val tabKeywords: List<String> = listOf("tab", "Tab", "换行", "制表符", "切换", "タブ", "탭")

    // ==================== 公共方法 ====================

    /**
     * JADX m212601a0 → accessibilityKeywordsList
     * Returns accessibility-related keywords (f55769b9)
     */
    fun accessibilityKeywordsList(): List<String> = accessibilityKeywords

    /**
     * JADX m212602a1 → positiveActionKeywordsList
     * Returns combined positive action keywords (allow + enable + confirm + whileUsing + alwaysAllow), deduplicated
     */
    fun positiveActionKeywordsList(): List<String> {
        return (allowKeywords + enableKeywords + confirmKeywords + whileUsingKeywords + alwaysAllowKeywords).distinct()
    }

    /**
     * JADX m212603a2 → forceStopKeywordsList
     * Returns force stop keywords (f55762b2)
     */
    fun forceStopKeywordsList(): List<String> = forceStopKeywords

    /**
     * JADX m212604a3 → resetKeywordsList
     * Returns reset/factory keywords (f55756a6)
     */
    fun resetKeywordsList(): List<String> = resetKeywords

    /**
     * JADX m212605a4 → isPositiveActionText
     * Checks if the given text matches any positive action keyword (case-insensitive, equals or contains)
     */
    fun isPositiveActionText(text: String): Boolean {
        val lowerCase = text.trim().lowercase(Locale.ROOT)
        val keywords = (allowKeywords + whileUsingKeywords + alwaysAllowKeywords + confirmKeywords).distinct()
        for (kw in keywords) {
            val kwLower = kw.lowercase(Locale.ROOT)
            if (lowerCase == kwLower) return true
            if (lowerCase.contains(kwLower)) return true
        }
        return false
    }

    /**
     * JADX m212606a5 → isCancelText
     * Checks if the given text matches any cancel/deny keyword (case-insensitive, equals or contains)
     */
    fun isCancelText(text: String): Boolean {
        val lowerCase = text.trim().lowercase(Locale.ROOT)
        for (kw in cancelKeywords) {
            val kwLower = kw.lowercase(Locale.ROOT)
            if (lowerCase == kwLower) return true
            if (lowerCase.contains(kwLower)) return true
        }
        return false
    }
}
