<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EaodWorker</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <TargetFramework>net45</TargetFramework>
    <Prefer32Bit>True</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="DotNetZip">
      <HintPath>..\..\DotNetZip.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\..\Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>